# -*- coding: utf-8 -*-
"""Value reference tables, practical guides and glossary."""

LINK_TYPES = [
    ("alternate", "link, a, area", "An alternate version of the document: another language (with hreflang), another format (RSS feed, PDF), or an alternate style sheet (with stylesheet)."),
    ("author", "link, a, area", "A page about the author of the document or article."),
    ("bookmark", "a, area", "A permalink to the nearest ancestor article."),
    ("canonical", "link", "The preferred URL of this page for search engines, avoiding duplicate content penalties."),
    ("dns-prefetch", "link", "Resolve the domain name of the given origin early."),
    ("expect", "link", "Block rendering until the element identified by href=\"#id\" is parsed (for view transitions)."),
    ("external", "a, area, form", "The link leads to a different site."),
    ("help", "link, a, area, form", "Context-sensitive help."),
    ("icon", "link", "The site icon (favicon). Combine with sizes and type. Also apple-touch-icon (non-standard) for iOS home screens."),
    ("license", "link, a, area, form", "The copyright licence covering the main content."),
    ("manifest", "link", "The web app manifest (JSON) for installable Progressive Web Apps."),
    ("me", "link, a, area", "The document represents the same person as the linked profile (IndieAuth / rel-me verification)."),
    ("modulepreload", "link", "Preload a JavaScript module and its dependencies."),
    ("next / prev", "link, a, area, form", "The next or previous document in a sequence (pagination, chapters)."),
    ("nofollow", "a, area, form", "The author does not endorse the linked page; search engines should not pass ranking credit."),
    ("noopener", "a, area, form", "Open the link without giving the new page access to window.opener. Implied by default for target=_blank in modern browsers."),
    ("noreferrer", "a, area, form", "Do not send the Referer header; also implies noopener."),
    ("opener", "a, area, form", "Explicitly allow window.opener for target=_blank."),
    ("pingback", "link", "The pingback server address for this document."),
    ("preconnect", "link", "Open a connection (DNS, TCP, TLS) to the origin early; use for fonts and APIs."),
    ("prefetch", "link", "Fetch a resource likely to be needed for the next navigation and store it in cache."),
    ("preload", "link", "Fetch a resource needed by the current page early with high priority. Requires as."),
    ("prerender", "link", "Deprecated; render a page in the background. Replaced by speculation rules."),
    ("privacy-policy", "link, a, area", "The privacy policy for the site."),
    ("search", "link, a, area, form", "A search interface for the site, often an OpenSearch description."),
    ("stylesheet", "link", "An external CSS style sheet. The most common link type."),
    ("tag", "a, area", "A tag (keyword) that applies to the current document."),
    ("terms-of-service", "link, a, area", "The terms of service for the site."),
]

META_NAMES = [
    ("application-name", "Short name of the web application the page belongs to."),
    ("author", "Name of the document's author."),
    ("description", "A short summary of the page, often shown under the title in search results. Aim for 50-160 characters."),
    ("generator", "Software that generated the page (for example a CMS)."),
    ("keywords", "Comma-separated keywords. Ignored by major search engines; historical."),
    ("referrer", "Default referrer policy for the document: no-referrer, origin, strict-origin-when-cross-origin, and so on."),
    ("theme-color", "Suggested colour for the browser UI (address bar on mobile). Accepts media."),
    ("color-scheme", "Colour schemes the page supports: light, dark, light dark, only light."),
    ("viewport", "Controls layout on mobile: width=device-width, initial-scale=1, plus optional minimum-scale, maximum-scale, user-scalable (do not disable zoom), viewport-fit=cover, interactive-widget."),
    ("robots", "Indexing directives: index/noindex, follow/nofollow, noarchive, nosnippet, max-snippet:n, max-image-preview:large, noimageindex, notranslate, unavailable_after."),
    ("googlebot / bingbot", "Same as robots but for one crawler."),
    ("google", "Google-specific: nositelinkssearchbox, notranslate."),
    ("rating", "Content rating: adult or RTA-5042-1996-1400-1577-RTA."),
    ("creator / publisher", "The creator and publisher of the document."),
    ("format-detection", "iOS: telephone=no stops phone numbers becoming links."),
    ("apple-mobile-web-app-capable / apple-mobile-web-app-status-bar-style / apple-mobile-web-app-title", "iOS home-screen app behaviour (non-standard)."),
    ("mobile-web-app-capable", "Android equivalent (non-standard)."),
    ("msapplication-TileColor / msapplication-config", "Windows tile settings (non-standard)."),
    ("twitter:card / twitter:site / twitter:title / twitter:description / twitter:image", "Twitter/X card metadata."),
    ("property=og:title / og:type / og:image / og:url / og:description / og:site_name / og:locale", "Open Graph metadata used by Facebook, LinkedIn, WhatsApp, Slack and others when a link is shared (uses property instead of name)."),
    ("http-equiv=content-type", "Legacy encoding declaration; use charset."),
    ("http-equiv=default-style", "Name of the preferred style sheet set."),
    ("http-equiv=refresh", "Reload after n seconds, optionally to another URL: content=\"5; url=...\"."),
    ("http-equiv=content-security-policy", "Content Security Policy for the page."),
    ("http-equiv=x-ua-compatible", "Legacy: content=\"IE=edge\" for Internet Explorer document mode."),
    ("http-equiv=content-language", "Obsolete; use lang on <html>."),
    ("http-equiv=set-cookie", "Obsolete; not allowed."),
]

AUTOCOMPLETE_TOKENS = [
    ("off", "Do not autofill (browsers may ignore for login fields)."), ("on", "Autofill allowed; browser guesses the field."),
    ("name", "Full name."), ("honorific-prefix", "Mr, Mrs, Dr..."), ("given-name", "First name."), ("additional-name", "Middle name."), ("family-name", "Last name."), ("honorific-suffix", "Jr, PhD..."), ("nickname", "Nickname."),
    ("username", "Account username."), ("new-password", "A new password (browser may suggest one)."), ("current-password", "Existing password for login."), ("one-time-code", "SMS/email verification code."),
    ("organization-title", "Job title."), ("organization", "Company name."),
    ("street-address", "Full street address (multi-line)."), ("address-line1 / address-line2 / address-line3", "Address lines."), ("address-level1", "Province / state / governorate."), ("address-level2", "City."), ("address-level3 / address-level4", "Finer divisions."), ("country", "Country code."), ("country-name", "Country name."), ("postal-code", "Postal / ZIP code."),
    ("cc-name", "Cardholder name."), ("cc-given-name / cc-additional-name / cc-family-name", "Cardholder name parts."), ("cc-number", "Card number."), ("cc-exp", "Expiry MM/YY."), ("cc-exp-month / cc-exp-year", "Expiry parts."), ("cc-csc", "Security code."), ("cc-type", "Card type."),
    ("transaction-currency", "Currency code."), ("transaction-amount", "Amount."),
    ("language", "Preferred language."), ("bday", "Birthday."), ("bday-day / bday-month / bday-year", "Birthday parts."), ("sex", "Gender identity as free text."),
    ("url", "Home page."), ("photo", "Photo URL."),
    ("tel", "Full telephone number."), ("tel-country-code / tel-national / tel-area-code / tel-local / tel-extension", "Telephone parts."),
    ("email", "Email address."), ("impp", "Instant messaging URL."),
    ("Prefixes: shipping / billing", "shipping street-address, billing postal-code..."), ("Prefixes: home / work / mobile / fax / pager", "home tel, work email..."),
    ("section-*", "Groups fields into a named section: section-guest1 name."),
    ("webauthn", "Allow passkey autofill (with username or current-password)."),
]

MIME_TYPES = [
    ("text/html", ".html .htm", "HTML documents"), ("text/css", ".css", "Style sheets"), ("text/javascript", ".js .mjs", "JavaScript (application/javascript is legacy)"),
    ("application/json", ".json", "JSON data"), ("application/ld+json", ".jsonld", "JSON-LD structured data"), ("application/xml, text/xml", ".xml", "XML"), ("image/svg+xml", ".svg", "SVG images"),
    ("text/plain", ".txt", "Plain text"), ("text/csv", ".csv", "Comma-separated values"), ("text/vtt", ".vtt", "WebVTT subtitles"), ("text/markdown", ".md", "Markdown"),
    ("image/jpeg", ".jpg .jpeg", "Photos"), ("image/png", ".png", "Lossless images with transparency"), ("image/gif", ".gif", "Simple animations"), ("image/webp", ".webp", "Modern lossy/lossless"), ("image/avif", ".avif", "Newest, smallest"), ("image/apng", ".apng", "Animated PNG"), ("image/x-icon, image/vnd.microsoft.icon", ".ico", "Favicons"), ("image/bmp", ".bmp", "Bitmap"), ("image/tiff", ".tif", "TIFF (not displayed by browsers)"),
    ("audio/mpeg", ".mp3", "MP3 audio"), ("audio/ogg", ".ogg .oga .opus", "Ogg Vorbis / Opus"), ("audio/wav", ".wav", "Uncompressed audio"), ("audio/aac", ".aac", "AAC"), ("audio/flac", ".flac", "Lossless"), ("audio/webm", ".weba", "WebM audio"), ("audio/midi", ".mid", "MIDI"),
    ("video/mp4", ".mp4 .m4v", "H.264/H.265 video"), ("video/webm", ".webm", "VP8/VP9/AV1 video"), ("video/ogg", ".ogv", "Theora"), ("video/quicktime", ".mov", "QuickTime"), ("video/x-msvideo", ".avi", "AVI"), ("application/x-mpegURL", ".m3u8", "HLS streaming playlist"),
    ("font/woff2", ".woff2", "Web fonts (best)"), ("font/woff", ".woff", "Web fonts"), ("font/ttf", ".ttf", "TrueType"), ("font/otf", ".otf", "OpenType"),
    ("application/pdf", ".pdf", "PDF"), ("application/zip", ".zip", "ZIP"), ("application/gzip", ".gz", "Gzip"), ("application/octet-stream", "any", "Generic binary; forces download"),
    ("application/msword", ".doc", "Word 97-2003"), ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx", "Word"), ("application/vnd.ms-excel", ".xls", "Excel 97-2003"), ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx", "Excel"), ("application/vnd.ms-powerpoint", ".ppt", "PowerPoint"), ("application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx", "PowerPoint"),
    ("application/x-www-form-urlencoded", "-", "Default form encoding"), ("multipart/form-data", "-", "Form encoding for file uploads"), ("text/event-stream", "-", "Server-sent events"), ("application/wasm", ".wasm", "WebAssembly"), ("application/manifest+json", ".webmanifest", "Web app manifest"), ("application/rss+xml / application/atom+xml", ".rss .atom", "Feeds"),
]

URL_SCHEMES = [
    ("https:", "Secure web page. Always use for links and resources."), ("http:", "Insecure web page."), ("mailto:", "Opens the mail client: mailto:a@b.com?subject=Hi&body=Text&cc=c@d.com"),
    ("tel:", "Dials a telephone number: tel:+201001234567"), ("sms:", "Opens SMS: sms:+2010...?body=Hello"), ("ftp:", "File transfer (no longer supported by browsers)."),
    ("file:", "A local file (only works locally)."), ("data:", "Inline data: data:image/png;base64,....  or data:text/plain,Hello"), ("blob:", "An object URL created with URL.createObjectURL()."),
    ("javascript:", "Runs script when followed. Avoid; use a button."), ("about:", "Browser pages: about:blank."), ("geo:", "Geographic coordinates: geo:30.0131,31.2089"),
    ("whatsapp: / tg: / skype:", "App links (non-standard)."), ("web+name:", "Custom schemes registered with registerProtocolHandler."), ("#fragment", "Not a scheme: a link to an id in the current page. #top and empty # scroll to the top."),
]

COLOR_NAMES = [
    ("aliceblue", "#f0f8ff"), ("antiquewhite", "#faebd7"), ("aqua", "#00ffff"), ("aquamarine", "#7fffd4"), ("azure", "#f0ffff"), ("beige", "#f5f5dc"), ("bisque", "#ffe4c4"), ("black", "#000000"), ("blanchedalmond", "#ffebcd"), ("blue", "#0000ff"), ("blueviolet", "#8a2be2"), ("brown", "#a52a2a"), ("burlywood", "#deb887"), ("cadetblue", "#5f9ea0"), ("chartreuse", "#7fff00"), ("chocolate", "#d2691e"), ("coral", "#ff7f50"), ("cornflowerblue", "#6495ed"), ("cornsilk", "#fff8dc"), ("crimson", "#dc143c"), ("cyan", "#00ffff"), ("darkblue", "#00008b"), ("darkcyan", "#008b8b"), ("darkgoldenrod", "#b8860b"), ("darkgray", "#a9a9a9"), ("darkgreen", "#006400"), ("darkkhaki", "#bdb76b"), ("darkmagenta", "#8b008b"), ("darkolivegreen", "#556b2f"), ("darkorange", "#ff8c00"), ("darkorchid", "#9932cc"), ("darkred", "#8b0000"), ("darksalmon", "#e9967a"), ("darkseagreen", "#8fbc8f"), ("darkslateblue", "#483d8b"), ("darkslategray", "#2f4f4f"), ("darkturquoise", "#00ced1"), ("darkviolet", "#9400d3"), ("deeppink", "#ff1493"), ("deepskyblue", "#00bfff"), ("dimgray", "#696969"), ("dodgerblue", "#1e90ff"), ("firebrick", "#b22222"), ("floralwhite", "#fffaf0"), ("forestgreen", "#228b22"), ("fuchsia", "#ff00ff"), ("gainsboro", "#dcdcdc"), ("ghostwhite", "#f8f8ff"), ("gold", "#ffd700"), ("goldenrod", "#daa520"), ("gray", "#808080"), ("green", "#008000"), ("greenyellow", "#adff2f"), ("honeydew", "#f0fff0"), ("hotpink", "#ff69b4"), ("indianred", "#cd5c5c"), ("indigo", "#4b0082"), ("ivory", "#fffff0"), ("khaki", "#f0e68c"), ("lavender", "#e6e6fa"), ("lavenderblush", "#fff0f5"), ("lawngreen", "#7cfc00"), ("lemonchiffon", "#fffacd"), ("lightblue", "#add8e6"), ("lightcoral", "#f08080"), ("lightcyan", "#e0ffff"), ("lightgoldenrodyellow", "#fafad2"), ("lightgray", "#d3d3d3"), ("lightgreen", "#90ee90"), ("lightpink", "#ffb6c1"), ("lightsalmon", "#ffa07a"), ("lightseagreen", "#20b2aa"), ("lightskyblue", "#87cefa"), ("lightslategray", "#778899"), ("lightsteelblue", "#b0c4de"), ("lightyellow", "#ffffe0"), ("lime", "#00ff00"), ("limegreen", "#32cd32"), ("linen", "#faf0e6"), ("magenta", "#ff00ff"), ("maroon", "#800000"), ("mediumaquamarine", "#66cdaa"), ("mediumblue", "#0000cd"), ("mediumorchid", "#ba55d3"), ("mediumpurple", "#9370db"), ("mediumseagreen", "#3cb371"), ("mediumslateblue", "#7b68ee"), ("mediumspringgreen", "#00fa9a"), ("mediumturquoise", "#48d1cc"), ("mediumvioletred", "#c71585"), ("midnightblue", "#191970"), ("mintcream", "#f5fffa"), ("mistyrose", "#ffe4e1"), ("moccasin", "#ffe4b5"), ("navajowhite", "#ffdead"), ("navy", "#000080"), ("oldlace", "#fdf5e6"), ("olive", "#808000"), ("olivedrab", "#6b8e23"), ("orange", "#ffa500"), ("orangered", "#ff4500"), ("orchid", "#da70d6"), ("palegoldenrod", "#eee8aa"), ("palegreen", "#98fb98"), ("paleturquoise", "#afeeee"), ("palevioletred", "#db7093"), ("papayawhip", "#ffefd5"), ("peachpuff", "#ffdab9"), ("peru", "#cd853f"), ("pink", "#ffc0cb"), ("plum", "#dda0dd"), ("powderblue", "#b0e0e6"), ("purple", "#800080"), ("rebeccapurple", "#663399"), ("red", "#ff0000"), ("rosybrown", "#bc8f8f"), ("royalblue", "#4169e1"), ("saddlebrown", "#8b4513"), ("salmon", "#fa8072"), ("sandybrown", "#f4a460"), ("seagreen", "#2e8b57"), ("seashell", "#fff5ee"), ("sienna", "#a0522d"), ("silver", "#c0c0c0"), ("skyblue", "#87ceeb"), ("slateblue", "#6a5acd"), ("slategray", "#708090"), ("snow", "#fffafa"), ("springgreen", "#00ff7f"), ("steelblue", "#4682b4"), ("tan", "#d2b48c"), ("teal", "#008080"), ("thistle", "#d8bfd8"), ("tomato", "#ff6347"), ("turquoise", "#40e0d0"), ("violet", "#ee82ee"), ("wheat", "#f5deb3"), ("white", "#ffffff"), ("whitesmoke", "#f5f5f5"), ("yellow", "#ffff00"), ("yellowgreen", "#9acd32"),
]

# (name, code, char description)
ENTITIES = [
    ("&amp;", "&#38;", "& ampersand"), ("&lt;", "&#60;", "< less-than"), ("&gt;", "&#62;", "> greater-than"), ("&quot;", "&#34;", "\" double quote"), ("&apos;", "&#39;", "' apostrophe"),
    ("&nbsp;", "&#160;", "non-breaking space"), ("&ensp;", "&#8194;", "en space"), ("&emsp;", "&#8195;", "em space"), ("&thinsp;", "&#8201;", "thin space"), ("&zwnj;", "&#8204;", "zero-width non-joiner"), ("&zwj;", "&#8205;", "zero-width joiner"), ("&shy;", "&#173;", "soft hyphen"), ("&lrm;", "&#8206;", "left-to-right mark"), ("&rlm;", "&#8207;", "right-to-left mark"),
    ("&copy;", "&#169;", "\u00a9 copyright"), ("&reg;", "&#174;", "\u00ae registered"), ("&trade;", "&#8482;", "\u2122 trademark"), ("&sect;", "&#167;", "\u00a7 section"), ("&para;", "&#182;", "\u00b6 pilcrow"), ("&deg;", "&#176;", "\u00b0 degree"), ("&micro;", "&#181;", "\u00b5 micro"), ("&middot;", "&#183;", "\u00b7 middle dot"), ("&bull;", "&#8226;", "\u2022 bullet"), ("&hellip;", "&#8230;", "\u2026 ellipsis"), ("&dagger;", "&#8224;", "\u2020 dagger"), ("&Dagger;", "&#8225;", "\u2021 double dagger"), ("&permil;", "&#8240;", "\u2030 per mille"), ("&prime;", "&#8242;", "\u2032 prime"), ("&Prime;", "&#8243;", "\u2033 double prime"),
    ("&ndash;", "&#8211;", "\u2013 en dash"), ("&mdash;", "&#8212;", "\u2014 em dash"), ("&lsquo;", "&#8216;", "\u2018 left single quote"), ("&rsquo;", "&#8217;", "\u2019 right single quote"), ("&sbquo;", "&#8218;", "\u201a single low quote"), ("&ldquo;", "&#8220;", "\u201c left double quote"), ("&rdquo;", "&#8221;", "\u201d right double quote"), ("&bdquo;", "&#8222;", "\u201e double low quote"), ("&laquo;", "&#171;", "\u00ab left guillemet"), ("&raquo;", "&#187;", "\u00bb right guillemet"), ("&lsaquo;", "&#8249;", "\u2039 single left guillemet"), ("&rsaquo;", "&#8250;", "\u203a single right guillemet"), ("&iexcl;", "&#161;", "\u00a1 inverted exclamation"), ("&iquest;", "&#191;", "\u00bf inverted question"),
    ("&cent;", "&#162;", "\u00a2 cent"), ("&pound;", "&#163;", "\u00a3 pound"), ("&curren;", "&#164;", "\u00a4 currency"), ("&yen;", "&#165;", "\u00a5 yen"), ("&euro;", "&#8364;", "\u20ac euro"), ("&#8378;", "&#8378;", "\u20ba lira"), ("&#8377;", "&#8377;", "\u20b9 rupee"), ("&#8369;", "&#8369;", "\u20b1 peso"),
    ("&plusmn;", "&#177;", "\u00b1 plus-minus"), ("&times;", "&#215;", "\u00d7 multiplication"), ("&divide;", "&#247;", "\u00f7 division"), ("&minus;", "&#8722;", "\u2212 minus"), ("&frac12;", "&#189;", "\u00bd one half"), ("&frac14;", "&#188;", "\u00bc one quarter"), ("&frac34;", "&#190;", "\u00be three quarters"), ("&sup1;", "&#185;", "\u00b9 superscript 1"), ("&sup2;", "&#178;", "\u00b2 superscript 2"), ("&sup3;", "&#179;", "\u00b3 superscript 3"), ("&ne;", "&#8800;", "\u2260 not equal"), ("&le;", "&#8804;", "\u2264 less or equal"), ("&ge;", "&#8805;", "\u2265 greater or equal"), ("&asymp;", "&#8776;", "\u2248 approximately"), ("&equiv;", "&#8801;", "\u2261 identical"), ("&infin;", "&#8734;", "\u221e infinity"), ("&radic;", "&#8730;", "\u221a square root"), ("&sum;", "&#8721;", "\u2211 sum"), ("&prod;", "&#8719;", "\u220f product"), ("&int;", "&#8747;", "\u222b integral"), ("&part;", "&#8706;", "\u2202 partial"), ("&nabla;", "&#8711;", "\u2207 nabla"), ("&isin;", "&#8712;", "\u2208 element of"), ("&notin;", "&#8713;", "\u2209 not element of"), ("&sub;", "&#8834;", "\u2282 subset"), ("&sup;", "&#8835;", "\u2283 superset"), ("&cap;", "&#8745;", "\u2229 intersection"), ("&cup;", "&#8746;", "\u222a union"), ("&and;", "&#8743;", "\u2227 and"), ("&or;", "&#8744;", "\u2228 or"), ("&not;", "&#172;", "\u00ac not"), ("&forall;", "&#8704;", "\u2200 for all"), ("&exist;", "&#8707;", "\u2203 exists"), ("&empty;", "&#8709;", "\u2205 empty set"), ("&perp;", "&#8869;", "\u22a5 perpendicular"), ("&ang;", "&#8736;", "\u2220 angle"), ("&there4;", "&#8756;", "\u2234 therefore"), ("&prop;", "&#8733;", "\u221d proportional"), ("&fnof;", "&#402;", "\u0192 function"), ("&lowast;", "&#8727;", "\u2217 asterisk operator"), ("&sdot;", "&#8901;", "\u22c5 dot operator"), ("&oplus;", "&#8853;", "\u2295 circled plus"), ("&otimes;", "&#8855;", "\u2297 circled times"),
    ("&larr;", "&#8592;", "\u2190 left arrow"), ("&uarr;", "&#8593;", "\u2191 up arrow"), ("&rarr;", "&#8594;", "\u2192 right arrow"), ("&darr;", "&#8595;", "\u2193 down arrow"), ("&harr;", "&#8596;", "\u2194 left-right arrow"), ("&crarr;", "&#8629;", "\u21b5 carriage return"), ("&lArr;", "&#8656;", "\u21d0 double left arrow"), ("&uArr;", "&#8657;", "\u21d1 double up arrow"), ("&rArr;", "&#8658;", "\u21d2 double right arrow"), ("&dArr;", "&#8659;", "\u21d3 double down arrow"), ("&hArr;", "&#8660;", "\u21d4 double left-right arrow"),
    ("&spades;", "&#9824;", "\u2660 spade"), ("&clubs;", "&#9827;", "\u2663 club"), ("&hearts;", "&#9829;", "\u2665 heart"), ("&diams;", "&#9830;", "\u2666 diamond"), ("&loz;", "&#9674;", "\u25ca lozenge"), ("&#10003;", "&#10003;", "\u2713 check mark"), ("&#10007;", "&#10007;", "\u2717 ballot x"), ("&#9733;", "&#9733;", "\u2605 black star"), ("&#9734;", "&#9734;", "\u2606 white star"), ("&#9650;", "&#9650;", "\u25b2 up triangle"), ("&#9660;", "&#9660;", "\u25bc down triangle"), ("&#9679;", "&#9679;", "\u25cf black circle"), ("&#9632;", "&#9632;", "\u25a0 black square"),
    ("&Alpha; &alpha;", "&#913; &#945;", "\u0391 \u03b1 alpha"), ("&Beta; &beta;", "&#914; &#946;", "\u0392 \u03b2 beta"), ("&Gamma; &gamma;", "&#915; &#947;", "\u0393 \u03b3 gamma"), ("&Delta; &delta;", "&#916; &#948;", "\u0394 \u03b4 delta"), ("&Epsilon; &epsilon;", "&#917; &#949;", "\u0395 \u03b5 epsilon"), ("&Zeta; &zeta;", "&#918; &#950;", "\u0396 \u03b6 zeta"), ("&Eta; &eta;", "&#919; &#951;", "\u0397 \u03b7 eta"), ("&Theta; &theta;", "&#920; &#952;", "\u0398 \u03b8 theta"), ("&Iota; &iota;", "&#921; &#953;", "\u0399 \u03b9 iota"), ("&Kappa; &kappa;", "&#922; &#954;", "\u039a \u03ba kappa"), ("&Lambda; &lambda;", "&#923; &#955;", "\u039b \u03bb lambda"), ("&Mu; &mu;", "&#924; &#956;", "\u039c \u03bc mu"), ("&Nu; &nu;", "&#925; &#957;", "\u039d \u03bd nu"), ("&Xi; &xi;", "&#926; &#958;", "\u039e \u03be xi"), ("&Omicron; &omicron;", "&#927; &#959;", "\u039f \u03bf omicron"), ("&Pi; &pi;", "&#928; &#960;", "\u03a0 \u03c0 pi"), ("&Rho; &rho;", "&#929; &#961;", "\u03a1 \u03c1 rho"), ("&Sigma; &sigma; &sigmaf;", "&#931; &#963; &#962;", "\u03a3 \u03c3 \u03c2 sigma"), ("&Tau; &tau;", "&#932; &#964;", "\u03a4 \u03c4 tau"), ("&Upsilon; &upsilon;", "&#933; &#965;", "\u03a5 \u03c5 upsilon"), ("&Phi; &phi;", "&#934; &#966;", "\u03a6 \u03c6 phi"), ("&Chi; &chi;", "&#935; &#967;", "\u03a7 \u03c7 chi"), ("&Psi; &psi;", "&#936; &#968;", "\u03a8 \u03c8 psi"), ("&Omega; &omega;", "&#937; &#969;", "\u03a9 \u03c9 omega"),
    ("&Agrave; &agrave;", "&#192; &#224;", "\u00c0 \u00e0"), ("&Aacute; &aacute;", "&#193; &#225;", "\u00c1 \u00e1"), ("&Acirc; &acirc;", "&#194; &#226;", "\u00c2 \u00e2"), ("&Atilde; &atilde;", "&#195; &#227;", "\u00c3 \u00e3"), ("&Auml; &auml;", "&#196; &#228;", "\u00c4 \u00e4"), ("&Aring; &aring;", "&#197; &#229;", "\u00c5 \u00e5"), ("&AElig; &aelig;", "&#198; &#230;", "\u00c6 \u00e6"), ("&Ccedil; &ccedil;", "&#199; &#231;", "\u00c7 \u00e7"), ("&Egrave; &egrave;", "&#200; &#232;", "\u00c8 \u00e8"), ("&Eacute; &eacute;", "&#201; &#233;", "\u00c9 \u00e9"), ("&Ecirc; &ecirc;", "&#202; &#234;", "\u00ca \u00ea"), ("&Euml; &euml;", "&#203; &#235;", "\u00cb \u00eb"), ("&Igrave; &igrave;", "&#204; &#236;", "\u00cc \u00ec"), ("&Iacute; &iacute;", "&#205; &#237;", "\u00cd \u00ed"), ("&Icirc; &icirc;", "&#206; &#238;", "\u00ce \u00ee"), ("&Iuml; &iuml;", "&#207; &#239;", "\u00cf \u00ef"), ("&ETH; &eth;", "&#208; &#240;", "\u00d0 \u00f0"), ("&Ntilde; &ntilde;", "&#209; &#241;", "\u00d1 \u00f1"), ("&Ograve; &ograve;", "&#210; &#242;", "\u00d2 \u00f2"), ("&Oacute; &oacute;", "&#211; &#243;", "\u00d3 \u00f3"), ("&Ocirc; &ocirc;", "&#212; &#244;", "\u00d4 \u00f4"), ("&Otilde; &otilde;", "&#213; &#245;", "\u00d5 \u00f5"), ("&Ouml; &ouml;", "&#214; &#246;", "\u00d6 \u00f6"), ("&Oslash; &oslash;", "&#216; &#248;", "\u00d8 \u00f8"), ("&OElig; &oelig;", "&#338; &#339;", "\u0152 \u0153"), ("&Scaron; &scaron;", "&#352; &#353;", "\u0160 \u0161"), ("&Ugrave; &ugrave;", "&#217; &#249;", "\u00d9 \u00f9"), ("&Uacute; &uacute;", "&#218; &#250;", "\u00da \u00fa"), ("&Ucirc; &ucirc;", "&#219; &#251;", "\u00db \u00fb"), ("&Uuml; &uuml;", "&#220; &#252;", "\u00dc \u00fc"), ("&Yacute; &yacute;", "&#221; &#253;", "\u00dd \u00fd"), ("&Yuml; &yuml;", "&#376; &#255;", "\u0178 \u00ff"), ("&THORN; &thorn;", "&#222; &#254;", "\u00de \u00fe"), ("&szlig;", "&#223;", "\u00df sharp s"),
]

GUIDES = [
("Building a complete page step by step", [
    ("p", "This guide walks through building a small, correct web page using the elements from this book, in the order you would type them."),
    ("h3", "Step 1: The skeleton"),
    ("code", "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>My Book Store</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n<body>\n\n</body>\n</html>"),
    ("h3", "Step 2: Landmarks"),
    ("code", "<body>\n  <header>\n    <h1>My Book Store</h1>\n    <nav aria-label=\"Main\">\n      <ul>\n        <li><a href=\"index.html\" aria-current=\"page\">Home</a></li>\n        <li><a href=\"books.html\">Books</a></li>\n        <li><a href=\"contact.html\">Contact</a></li>\n      </ul>\n    </nav>\n  </header>\n\n  <main>\n    <!-- unique content goes here -->\n  </main>\n\n  <footer>\n    <p><small>&copy; 2026 My Book Store</small></p>\n  </footer>\n</body>"),
    ("h3", "Step 3: Content"),
    ("code", "<main>\n  <section aria-labelledby=\"new\">\n    <h2 id=\"new\">New this week</h2>\n    <article class=\"card\">\n      <img src=\"html-book.jpg\" alt=\"Cover of Learn HTML\" width=\"200\" height=\"300\">\n      <h3>Learn HTML</h3>\n      <p>A complete beginner's guide. <span class=\"price\">120 EGP</span></p>\n      <button type=\"button\">Add to cart</button>\n    </article>\n  </section>\n\n  <section aria-labelledby=\"prices\">\n    <h2 id=\"prices\">Price list</h2>\n    <table>\n      <caption>PDF books</caption>\n      <thead><tr><th scope=\"col\">Title</th><th scope=\"col\">Price (EGP)</th></tr></thead>\n      <tbody>\n        <tr><td>Learn HTML</td><td>120</td></tr>\n        <tr><td>Learn CSS</td><td>140</td></tr>\n      </tbody>\n    </table>\n  </section>\n</main>"),
    ("h3", "Step 4: A form"),
    ("code", "<section aria-labelledby=\"contact\">\n  <h2 id=\"contact\">Contact us</h2>\n  <form action=\"/contact\" method=\"post\">\n    <div class=\"field\">\n      <label for=\"name\">Name</label>\n      <input id=\"name\" name=\"name\" required autocomplete=\"name\">\n    </div>\n    <div class=\"field\">\n      <label for=\"email\">Email</label>\n      <input id=\"email\" name=\"email\" type=\"email\" required autocomplete=\"email\">\n    </div>\n    <div class=\"field\">\n      <label for=\"msg\">Message</label>\n      <textarea id=\"msg\" name=\"message\" rows=\"4\" required></textarea>\n    </div>\n    <button type=\"submit\">Send</button>\n  </form>\n</section>"),
    ("h3", "Step 5: The style sheet"),
    ("code", "/* style.css */\n*, *::before, *::after { box-sizing: border-box; }\nbody { margin: 0; font-family: system-ui, Arial, sans-serif; line-height: 1.6; color: #1b2431; background: #f6f1e7; }\nheader, main, footer { padding: 1rem; }\nheader { background: #fff; box-shadow: 0 1px 0 #e7ddcb; }\nnav ul { display: flex; gap: 1rem; list-style: none; padding: 0; margin: 0; }\nnav a[aria-current=\"page\"] { font-weight: bold; }\nmain { max-width: 960px; margin: 0 auto; }\n.card { background: #fff; border-radius: 12px; padding: 1rem; display: grid; gap: 0.5rem; max-width: 260px; }\n.price { color: #e60000; font-weight: bold; }\ntable { border-collapse: collapse; width: 100%; background: #fff; }\nth, td { padding: 0.5rem; border-bottom: 1px solid #e7ddcb; text-align: left; }\n.field { display: grid; gap: 0.25rem; margin-bottom: 1rem; }\ninput, textarea { padding: 0.5rem; border: 1px solid #ccc; border-radius: 6px; font: inherit; }\nbutton { background: #e60000; color: #fff; border: 0; border-radius: 6px; padding: 0.6rem 1.2rem; cursor: pointer; }\nfooter { text-align: center; color: #6b7280; }"),
    ("h3", "Step 6: Check it"),
    ("ul", ["Open the file in a browser and resize the window.", "Press Tab repeatedly: every link, input and button should receive a visible focus ring in a sensible order.",
            "Validate at validator.w3.org.", "Run Lighthouse (in Chrome DevTools) for accessibility and performance scores."]),
]),
("Lists in depth", [
    ("p", "HTML has three list elements: <ul> for unordered lists, <ol> for ordered lists and <dl> for description lists. Items of ul and ol are <li>; a dl uses <dt> for terms and <dd> for descriptions."),
    ("h3", "Choosing the right list"),
    ("table", [["Question", "Use"], ["Does the order matter (steps, ranking)?", "<ol>"], ["Is it a set of items where order is irrelevant?", "<ul>"], ["Are they name-value pairs (term and definition, label and data)?", "<dl>"], ["Is it a toolbar of actions?", "<menu>"], ["Is it navigation links?", "<nav> containing a <ul>"]]),
    ("h3", "Numbering control on ordered lists"),
    ("table", [["Attribute / CSS", "Effect", "Example"], ["type=\"1\"", "1, 2, 3 (default)", "<ol type=\"1\">"], ["type=\"a\" / \"A\"", "a, b, c / A, B, C", "<ol type=\"A\">"], ["type=\"i\" / \"I\"", "i, ii, iii / I, II, III", "<ol type=\"I\">"], ["start=\"5\"", "Begin at 5", "<ol start=\"5\">"], ["reversed", "Count down", "<ol reversed>"], ["<li value=\"10\">", "Set this item's number", ""], ["list-style-type: lower-greek", "CSS: alpha, beta, gamma", "ol { list-style-type: lower-greek; }"], ["list-style-type: arabic-indic", "CSS: Arabic-Indic digits", "ol { list-style-type: arabic-indic; }"]]),
    ("h3", "CSS list-style-type values"),
    ("p", "For <ul>: disc (default), circle, square, none, or any string such as '\u2192 '. For <ol>: decimal, decimal-leading-zero, lower-roman, upper-roman, lower-alpha, upper-alpha, lower-greek, armenian, georgian, arabic-indic, persian, bengali, devanagari, cjk-decimal, japanese-informal, and more. list-style-position: inside puts the marker inside the item's box; outside (default) hangs it in the margin. list-style-image: url(icon.svg) uses an image; ::marker is the modern way to style markers."),
    ("h3", "Nested lists"),
    ("code", "<ol>\n  <li>Prepare\n    <ul>\n      <li>Install an editor</li>\n      <li>Create a folder</li>\n    </ul>\n  </li>\n  <li>Write HTML\n    <ol type=\"a\">\n      <li>Skeleton</li>\n      <li>Content</li>\n    </ol>\n  </li>\n</ol>"),
    ("h3", "Description lists for metadata"),
    ("code", "<dl>\n  <dt>Author</dt><dd>Sara Ali</dd>\n  <dt>Published</dt><dd><time datetime=\"2026-09\">September 2026</time></dd>\n  <dt>Pages</dt><dd>2000</dd>\n</dl>"),
    ("h3", "Common mistakes"),
    ("ul", ["Text directly inside <ul> or <ol> that is not in an <li>.", "A nested list placed between <li> elements instead of inside one.", "Using <br> or paragraphs starting with '-' instead of a real list.", "Using <dl> for dialogue or for layout."]),
]),
("Tables in depth", [
    ("p", "Use tables for data whose meaning depends on rows and columns. A well-built table has a caption, header cells with scope, and grouped rows."),
    ("h3", "Element roles"),
    ("table", [["Element", "Role"], ["<table>", "The table container"], ["<caption>", "Title, first child"], ["<colgroup> / <col>", "Column groups for styling"], ["<thead>", "Header rows"], ["<tbody>", "Data rows (one or more)"], ["<tfoot>", "Summary rows"], ["<tr>", "A row"], ["<th>", "Header cell, with scope=col|row|colgroup|rowgroup"], ["<td>", "Data cell"]]),
    ("h3", "colspan and rowspan"),
    ("p", "colspan=\"n\" makes a cell span n columns; rowspan=\"n\" makes it span n rows. Every row must still add up to the same number of columns. Sketch the grid on paper for complex tables."),
    ("code", "<table>\n  <tr><th rowspan=\"2\">Product</th><th colspan=\"2\">Sales</th></tr>\n  <tr><th>2025</th><th>2026</th></tr>\n  <tr><td>Books</td><td>120</td><td>150</td></tr>\n</table>"),
    ("h3", "HTML 3.2/4 attributes and their CSS replacements"),
    ("table", [["Old attribute", "CSS replacement"], ["border=\"1\"", "th, td { border: 1px solid; }"], ["cellpadding=\"5\"", "th, td { padding: 5px; }"], ["cellspacing=\"0\"", "table { border-collapse: collapse; } or border-spacing: 0"], ["width=\"100%\"", "table { width: 100%; }"], ["bgcolor=\"#eee\"", "background-color: #eee"], ["align=\"center\" on table", "table { margin: 0 auto; }"], ["align=\"right\" on td", "td { text-align: right; }"], ["valign=\"top\"", "vertical-align: top"], ["nowrap", "white-space: nowrap"], ["summary=\"...\"", "<caption> or aria-describedby"]]),
    ("h3", "Making tables responsive"),
    ("ul", ["Wrap the table in a div with overflow-x: auto so it scrolls horizontally on phones.", "Hide less important columns on small screens with a media query.", "Stack cells into blocks with display: block and data-label attributes (see the CSS cookbook).", "Use font-variant-numeric: tabular-nums so digits line up."]),
    ("h3", "Sorting and filtering"),
    ("p", "HTML has no built-in sorting. Add it with JavaScript by reading rows from tbody, sorting the array and re-appending, and mark the sorted column header with aria-sort=\"ascending\" or \"descending\"."),
]),
("Forms in depth", [
    ("p", "A form collects input and sends it to a server or a script. Building a good form is mostly about labels, the right input types, validation and clear feedback."),
    ("h3", "Checklist"),
    ("ul", ["Every control has a <label> linked by for/id or wrapping.", "Every control that must be submitted has a name.", "Use the most specific type: email, tel, url, number, date, and so on.", "Use autocomplete tokens so browsers can fill in addresses and cards.",
            "Group radio buttons and checkboxes with <fieldset> and <legend>.", "Mark required fields with required and say so visibly.", "Use pattern with a title explaining the format.", "Show errors next to the field and link them with aria-describedby; do not rely on colour alone.",
            "Use method=\"post\" for anything that changes data; enctype=\"multipart/form-data\" for files.", "Validate again on the server; client validation is only a convenience."]),
    ("h3", "GET versus POST"),
    ("table", [["", "GET", "POST"], ["Data location", "In the URL (?a=1&b=2)", "In the request body"], ["Bookmarkable", "Yes", "No"], ["Size limit", "About 2000 characters", "Practically none"], ["Use for", "Searches, filters", "Logins, orders, uploads, anything with side effects"], ["Security", "Visible in history and logs", "Not in URL (still needs HTTPS)"]]),
    ("h3", "Built-in validation attributes"),
    ("table", [["Attribute", "Applies to", "Checks"], ["required", "Most inputs, select, textarea", "Not empty / selected"], ["minlength / maxlength", "Text-like inputs, textarea", "Length"], ["min / max", "number, range, date, time...", "Range"], ["step", "number, range, date, time...", "Granularity"], ["pattern", "text, search, url, tel, email, password", "Regular expression (whole value)"], ["type=email / url", "input", "Format"]]),
    ("h3", "Styling validation states"),
    ("code", "input:required { border-left: 3px solid #999; }\ninput:user-invalid { border-color: #b90000; }\ninput:user-valid { border-color: #0f8a4c; }\n.error { color: #b90000; font-size: 0.9em; }"),
    ("h3", "Custom validation messages"),
    ("code", "<input id=\"zip\" pattern=\"[0-9]{5}\" required>\n<script>\n  const zip = document.getElementById('zip');\n  zip.addEventListener('invalid', () => zip.setCustomValidity('Enter exactly five digits.'));\n  zip.addEventListener('input', () => zip.setCustomValidity(''));\n</script>"),
]),
("Semantic layout and accessibility", [
    ("p", "Semantic HTML means choosing elements for what they mean, not how they look. It is the foundation of accessibility: screen readers, keyboard navigation, reader modes and search engines all depend on it."),
    ("h3", "Landmark map"),
    ("table", [["Element", "Landmark role", "How many per page"], ["<header> (top level)", "banner", "1"], ["<nav>", "navigation", "Several; label each"], ["<main>", "main", "Exactly 1"], ["<aside>", "complementary", "Several"], ["<footer> (top level)", "contentinfo", "1"], ["<form> with a name", "form", "Several"], ["<search>", "search", "Several"], ["<section> with a name", "region", "Several"]]),
    ("h3", "Heading outline"),
    ("p", "One <h1> per page, then h2 for sections, h3 inside them and so on, never skipping levels. Users of screen readers navigate by headings more than by any other means."),
    ("h3", "Images"),
    ("ul", ["Informative image: alt describes the content.", "Functional image (in a link or button): alt describes the action.", "Decorative image: alt=\"\" (empty).", "Complex image (chart): short alt plus a full description in text or a linked page."]),
    ("h3", "Keyboard"),
    ("ul", ["Everything clickable must be reachable with Tab and operable with Enter or Space: use <a>, <button> and form controls, not <div onclick>.", "Never remove the focus outline without providing a visible replacement (:focus-visible).", "Provide a skip link to <main>.", "Manage focus in dialogs and after dynamic changes."]),
    ("h3", "Colour and motion"),
    ("ul", ["Text contrast at least 4.5:1 (3:1 for large text).", "Never convey information by colour alone.", "Respect prefers-reduced-motion; avoid flashing content."]),
    ("h3", "ARIA in three rules"),
    ("ul", ["Do not use ARIA if a native element does the job.", "Do not change native semantics unless you must.", "All interactive ARIA controls must be keyboard usable."]),
]),
("Media: images, audio and video", [
    ("h3", "Choosing an image format"),
    ("table", [["Format", "Best for", "Notes"], ["AVIF", "Photos, smallest files", "Newest; use with fallback"], ["WebP", "Photos and graphics", "Widely supported"], ["JPEG", "Photos, universal fallback", "No transparency"], ["PNG", "Screenshots, logos with transparency", "Large for photos"], ["SVG", "Icons, logos, diagrams", "Scales perfectly; can be styled"], ["GIF", "Simple animations", "Prefer video or animated WebP/AVIF"]]),
    ("h3", "Responsive image decision"),
    ("ul", ["Same image, different sizes: <img srcset sizes>.", "Different crops or formats: <picture> with <source>.", "High-DPI only: srcset with 1x/2x.", "Always: alt, width, height, and loading=\"lazy\" below the fold."]),
    ("h3", "Audio and video checklist"),
    ("ul", ["Provide MP4 (H.264) plus WebM.", "Add controls.", "Add <track kind=\"captions\">.", "Set poster and preload=\"metadata\".", "For background video: autoplay muted loop playsinline, and pause it for prefers-reduced-motion.", "Provide a transcript."]),
    ("h3", "Embedding third-party media"),
    ("p", "YouTube, Vimeo and maps are embedded with <iframe>. Always add title, loading=\"lazy\" and only the allow permissions you need. Consider a click-to-load facade to save bandwidth."),
]),
("SEO essentials in HTML", [
    ("ul", ["Unique, descriptive <title> under 60 characters.", "<meta name=\"description\"> under 160 characters.", "One <h1> matching the page topic; logical heading structure.", "Semantic landmarks so crawlers understand the page.",
            "Descriptive link text; internal links between related pages.", "alt text on images; descriptive file names.", "<link rel=\"canonical\"> to avoid duplicates; hreflang alternates for translations.",
            "Structured data with JSON-LD (schema.org) for rich results.", "Fast loading: compressed images, lazy loading, deferred scripts, preconnect for fonts.", "Mobile friendly: the viewport meta tag and responsive CSS.", "Open Graph and Twitter tags for attractive sharing previews."]),
]),
("Migrating old HTML (2, 3.2, 4) to HTML5", [
    ("table", [["Old", "New"], ["<!DOCTYPE HTML PUBLIC ...>", "<!DOCTYPE html>"], ["<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">", "<meta charset=\"utf-8\">"], ["<script type=\"text/javascript\">", "<script>"], ["<style type=\"text/css\">", "<style>"],
            ["<font size color face>", "CSS font-size, color, font-family"], ["<center>", "CSS text-align: center / margin: auto"], ["<b> for importance", "<strong>"], ["<i> for emphasis", "<em>"], ["<u>", "CSS text-decoration or <ins>"], ["<strike>", "<s> or <del>"], ["<tt>", "<code>, <kbd>, <samp>"], ["<big>", "CSS font-size"],
            ["<div id=\"header\">", "<header>"], ["<div id=\"nav\">", "<nav>"], ["<div id=\"content\">", "<main>"], ["<div class=\"sidebar\">", "<aside>"], ["<div id=\"footer\">", "<footer>"], ["<div class=\"post\">", "<article>"],
            ["<table> for layout", "CSS grid / flexbox"], ["<frameset> / <frame>", "CSS layout; <iframe> if needed"], ["<applet>, <embed> Flash", "<video>, <audio>, <canvas>, JavaScript"], ["<a name=\"x\">", "id=\"x\" on any element"], ["<acronym>", "<abbr>"], ["<dir>, <menu> as list", "<ul>"],
            ["align, bgcolor, border, cellpadding, valign, width attributes", "CSS"], ["<br clear=\"all\">", "CSS clear or flow-root"], ["<img border=\"0\">", "img { border: 0 } (default now)"], ["onclick=\"javascript:...\"", "addEventListener in a script"]]),
]),
]

GLOSSARY = [
    ("Accessibility (a11y)", "Designing pages so that people with disabilities can use them, including with screen readers, keyboards, magnifiers and voice control."),
    ("ARIA", "Accessible Rich Internet Applications: a set of role and aria-* attributes that describe widgets and states to assistive technology."),
    ("Attribute", "A name=value pair inside an opening tag that configures the element, for example href=\"page.html\"."),
    ("Block-level element", "An element that starts on a new line and fills the available width, such as <div>, <p>, <h1>, <footer>."),
    ("Boolean attribute", "An attribute whose presence means true and absence means false, such as disabled, checked, required."),
    ("Browser", "The program that reads HTML, CSS and JavaScript and displays web pages: Chrome, Firefox, Safari, Edge."),
    ("Cascade", "The CSS mechanism that decides which of several conflicting rules applies, based on importance, specificity and order."),
    ("Character reference / entity", "A way to write a character by name or number, such as &amp; or &#169;."),
    ("Child / parent / sibling / ancestor / descendant", "Family terms describing element nesting in the document tree."),
    ("Class", "A reusable label applied with the class attribute and targeted in CSS with a dot: .name."),
    ("Content model", "The rules stating which children an element may contain."),
    ("CSS", "Cascading Style Sheets: the language that describes presentation."),
    ("Deprecated", "Still supported but discouraged; may be removed in future."),
    ("DOCTYPE", "The declaration at the top of a document (<!DOCTYPE html>) that switches the browser to standards mode."),
    ("DOM", "Document Object Model: the tree of objects the browser builds from HTML, which JavaScript can read and modify."),
    ("Element", "An opening tag, its content and its closing tag together (or a void tag alone)."),
    ("Empty / void element", "An element with no content and no closing tag, such as <br>, <img>, <input>."),
    ("Flow content", "Elements allowed in the body: most elements."),
    ("Focus", "The state of the element that currently receives keyboard input, moved with Tab."),
    ("Fragment", "The part of a URL after #, pointing to an element id."),
    ("Global attribute", "An attribute allowed on every element, such as id, class, style, title, lang, hidden."),
    ("HTML", "HyperText Markup Language: the language that structures web pages."),
    ("HTTP / HTTPS", "The protocol browsers use to fetch pages; HTTPS is the encrypted version."),
    ("Hyperlink", "A reference to another resource that the user can follow, created with <a href>."),
    ("Id", "A unique identifier for one element, targeted in CSS with # and in links with #."),
    ("Inline element", "An element that flows within text and takes only the width of its content: <span>, <a>, <em>."),
    ("JavaScript", "The programming language of the web, which adds behaviour to pages."),
    ("Landmark", "A region of the page (banner, navigation, main, contentinfo...) that assistive technology can jump to."),
    ("Living Standard", "The continuously updated HTML specification maintained by the WHATWG."),
    ("MDN", "Mozilla Developer Network (developer.mozilla.org), the most complete free web documentation."),
    ("Metadata", "Data about the document, placed in <head>."),
    ("MIME type", "A label such as text/html or image/png that identifies the type of a file."),
    ("Nesting", "Placing elements inside other elements."),
    ("Obsolete", "Removed from the standard; must not be used."),
    ("Phrasing content", "Text and inline elements that can appear inside a paragraph."),
    ("Pseudo-class / pseudo-element", "CSS selectors for states (:hover) or generated parts (::before)."),
    ("Quirks mode", "A compatibility rendering mode triggered by a missing DOCTYPE that imitates 1990s browser bugs."),
    ("Rendering", "The process of turning HTML and CSS into pixels."),
    ("Responsive design", "Layouts that adapt to any screen size, using fluid widths, flexible images and media queries."),
    ("Screen reader", "Software that reads the page aloud or in braille for blind users (NVDA, JAWS, VoiceOver, TalkBack)."),
    ("Sectioning content", "<article>, <aside>, <nav>, <section>: elements that define the scope of headings and footers."),
    ("Selector", "The part of a CSS rule that chooses which elements to style."),
    ("Semantic HTML", "Using elements according to their meaning."),
    ("Specificity", "The weight of a CSS selector, used by the cascade to resolve conflicts."),
    ("Tag", "The markup in angle brackets, <p> or </p>, that starts or ends an element."),
    ("URL", "Uniform Resource Locator: the address of a resource on the web."),
    ("UTF-8", "The character encoding that supports every language; always use it."),
    ("Validator", "A tool that checks HTML for errors (validator.w3.org)."),
    ("Viewport", "The visible area of the page in the browser window."),
    ("W3C", "World Wide Web Consortium, the standards body that published HTML 3.2 to HTML 5.2."),
    ("WCAG", "Web Content Accessibility Guidelines, the international accessibility standard."),
    ("WHATWG", "The browser vendor group that maintains the HTML Living Standard."),
    ("XHTML", "HTML written with XML syntax rules."),
]
