# -*- coding: utf-8 -*-
"""JavaScript part: fundamentals (block lists), a reference of the most used built-ins and DOM APIs, and course lessons."""

JS_INTRO = [
    ("p", "JavaScript is the third language of the web. HTML gives structure, CSS gives appearance, JavaScript gives behaviour: "
          "it reacts to clicks and typing, changes the page without reloading, checks forms, fetches data and stores settings. "
          "Every browser runs it; no installation is needed. This part covers the language from zero and the browser APIs you "
          "use with HTML and CSS. Everything here is written for a beginner who already knows the HTML and CSS parts of this book."),
    ("h2", "1. Adding JavaScript to a page"),
    ("code", "<!-- 1. External file (recommended). defer runs it after the HTML is parsed. -->\n<script src=\"app.js\" defer></script>\n\n<!-- 2. Inline script, usually at the end of <body> -->\n<script>\n  console.log('Hello from the page');\n</script>\n\n<!-- 3. Module: allows import/export, always deferred, strict mode -->\n<script type=\"module\" src=\"main.js\"></script>"),
    ("ul", ["Put <script defer> in the <head> or a plain <script> at the end of <body>; either way the elements exist when your code runs.",
            "Open the browser console (F12, Console tab) to see console.log output and error messages with line numbers.",
            "Never write behaviour in onclick attributes; keep JavaScript in files and attach handlers with addEventListener."]),
    ("h2", "2. Syntax basics"),
    ("code", "// A comment. Statements end with a semicolon.\n/* A multi-line\n   comment */\nlet count = 0;            // variable that can change\nconst name = 'Mohamed';   // constant: cannot be reassigned\ncount = count + 1;        // 1\ncount += 1;               // 2\nconsole.log(name, count); // prints: Mohamed 2"),
    ("table", [["Rule", "Detail"], ["Case sensitive", "total, Total and TOTAL are different names"], ["Names", "Letters, digits, _ and $; cannot start with a digit; use camelCase: firstName"],
               ["Strings", "'single' or \"double\" quotes, or `backticks` for templates with ${expression}"], ["Semicolons", "Optional but recommended at the end of statements"],
               ["Blocks", "Curly braces { } group statements (if, loops, functions)"], ["Strict mode", "'use strict'; at the top (automatic in modules) catches common mistakes"]]),
    ("h2", "3. Values and types"),
    ("table", [["Type", "Examples", "Notes"], ["number", "42, 3.14, -7, NaN, Infinity", "One numeric type; 0.1 + 0.2 is 0.30000000000000004"],
               ["string", "'hi', \"hi\", `hi ${name}`", "Text; immutable; .length gives the number of characters"], ["boolean", "true, false", "Result of comparisons"],
               ["undefined", "let x; // x is undefined", "Declared but no value"], ["null", "let user = null;", "Intentional 'no value'"],
               ["object", "{ name: 'Sara', age: 30 }", "Key/value pairs"], ["array", "[1, 2, 3]", "Ordered list (a kind of object)"],
               ["function", "function f() {}", "Callable code (also a kind of object)"], ["bigint, symbol", "123n, Symbol('id')", "Rare in beginner code"]]),
    ("code", "typeof 42          // 'number'\ntypeof 'a'         // 'string'\ntypeof true        // 'boolean'\ntypeof undefined   // 'undefined'\ntypeof null        // 'object'  (a famous historical bug)\ntypeof [1, 2]      // 'object'  (use Array.isArray)\ntypeof (() => 1)   // 'function'"),
    ("h2", "4. Operators"),
    ("table", [["Operator", "Meaning", "Example"], ["+ - * / %", "Arithmetic; % is remainder", "7 % 3 is 1"], ["**", "Power", "2 ** 10 is 1024"],
               ["++ --", "Increment / decrement", "i++"], ["= += -= *= /=", "Assignment", "x += 5"], ["=== !==", "Strict equality / inequality (use these)", "1 === '1' is false"],
               ["== !=", "Loose equality (converts types; avoid)", "1 == '1' is true"], ["< > <= >=", "Comparison", "age >= 18"],
               ["&& || !", "And, or, not", "isOpen && !isFull"], ["??", "Nullish coalescing: right side if left is null/undefined", "name ?? 'Guest'"],
               ["?.", "Optional chaining: stops if null/undefined", "user?.address?.city"], ["? :", "Ternary conditional", "age >= 18 ? 'adult' : 'minor'"],
               ["+ with strings", "Concatenation", "'Total: ' + 5 is 'Total: 5'"], ["typeof, instanceof, in", "Type checks", "'name' in user"]]),
    ("h2", "5. Control flow"),
    ("code", "if (score >= 90) {\n  grade = 'A';\n} else if (score >= 80) {\n  grade = 'B';\n} else {\n  grade = 'C';\n}\n\nswitch (day) {\n  case 'Fri':\n  case 'Sat':\n    console.log('Weekend');\n    break;\n  default:\n    console.log('Work day');\n}\n\nfor (let i = 0; i < 5; i++) { console.log(i); }       // 0 1 2 3 4\nfor (const item of items) { console.log(item); }      // each value of an array\nfor (const key in obj) { console.log(key, obj[key]); } // each key of an object\nwhile (queue.length > 0) { queue.pop(); }\ndo { attempts++; } while (attempts < 3);\n// break leaves a loop; continue skips to the next turn"),
    ("p", "Truthiness: in a condition, these values count as false: false, 0, '', null, undefined, NaN. Everything else, including '0', [] and {}, counts as true."),
    ("h2", "6. Functions"),
    ("code", "// Declaration (hoisted: can be called before it appears)\nfunction add(a, b) {\n  return a + b;\n}\n\n// Expression and arrow function\nconst multiply = (a, b) => a * b;      // implicit return\nconst greet = name => `Hello, ${name}`;\nconst log = () => { console.log('hi'); };\n\n// Default parameters and rest parameters\nfunction price(amount, currency = 'EGP') { return `${amount} ${currency}`; }\nfunction sum(...numbers) { return numbers.reduce((t, n) => t + n, 0); }\n\nadd(2, 3);        // 5\nsum(1, 2, 3, 4);  // 10"),
    ("ul", ["A function that does not return anything returns undefined.", "Arrow functions do not have their own this; use them for callbacks.",
            "Functions are values: you can store them in variables, pass them to other functions (callbacks) and return them.",
            "Scope: variables declared with let/const inside a block { } exist only there. Avoid var (function scoped, hoisted)."]),
    ("h2", "7. Arrays"),
    ("code", "const books = ['HTML', 'CSS', 'JS'];\nbooks.length            // 3\nbooks[0]                // 'HTML'  (indexes start at 0)\nbooks.at(-1)            // 'JS'    (last)\nbooks.push('SQL');      // add to end -> 4\nbooks.pop();            // remove last -> 'SQL'\nbooks.unshift('Intro'); // add to start\nbooks.shift();          // remove first\nbooks.includes('CSS')   // true\nbooks.indexOf('CSS')    // 1\nbooks.join(', ')        // 'HTML, CSS, JS'\nbooks.slice(0, 2)       // ['HTML', 'CSS']  (copy part)\nbooks.splice(1, 1)      // removes 1 item at index 1 (changes the array)\n\n// The big three: map, filter, reduce (do not change the original)\nconst prices = [120, 150, 180];\nprices.map(p => p * 0.9)                 // [108, 135, 162]\nprices.filter(p => p > 130)              // [150, 180]\nprices.reduce((sum, p) => sum + p, 0)    // 450\nprices.find(p => p > 130)                // 150\nprices.some(p => p > 170)                // true\nprices.every(p => p > 100)               // true\n[...prices].sort((a, b) => a - b)        // sorted copy (sort without a function sorts as text!)\nprices.forEach((p, i) => console.log(i, p));"),
    ("h2", "8. Objects"),
    ("code", "const book = {\n  title: 'Learn HTML',\n  price: 120,\n  tags: ['web', 'beginner'],\n  author: { name: 'Sara', city: 'Cairo' },\n  discounted(percent) { return this.price * (1 - percent / 100); }\n};\nbook.title             // 'Learn HTML'\nbook['price']          // 120  (bracket form, useful with variables)\nbook.author.city       // 'Cairo'\nbook.pages = 300;      // add a property\ndelete book.tags;      // remove one\nbook.discounted(10)    // 108\n\nObject.keys(book)      // ['title', 'price', ...]\nObject.values(book)\nObject.entries(book)   // [['title', 'Learn HTML'], ...]\n\n// Destructuring and spread\nconst { title, price } = book;\nconst copy = { ...book, price: 99 };   // shallow copy with a change\nconst [first, second] = ['a', 'b'];\n\n// JSON: text format for storing and sending objects\nconst text = JSON.stringify(book);     // '{\"title\":\"Learn HTML\",...}'\nconst again = JSON.parse(text);"),
    ("h2", "9. Strings"),
    ("code", "const s = 'Cairo Book Shop';\ns.length               // 15\ns.toUpperCase()        // 'CAIRO BOOK SHOP'\ns.toLowerCase()\ns.includes('Book')     // true\ns.startsWith('Cairo')  // true\ns.indexOf('Book')      // 6\ns.slice(0, 5)          // 'Cairo'\ns.split(' ')           // ['Cairo', 'Book', 'Shop']\ns.replace('Shop', 'Store')\ns.replaceAll('o', '0')\n'  x  '.trim()         // 'x'\n'5'.padStart(3, '0')   // '005'\n`Total: ${2 * 60} EGP` // 'Total: 120 EGP'  (template literal)\nNumber('42')           // 42\nparseFloat('3.5kg')    // 3.5\n(1234.5).toFixed(2)    // '1234.50'\n(1234567).toLocaleString('en-EG')  // '1,234,567'"),
    ("h2", "10. The DOM: finding and changing elements"),
    ("p", "The Document Object Model is the browser's live tree of your HTML. JavaScript reads and changes it; the page updates immediately."),
    ("code", "// Find elements (CSS selectors, exactly as in your style sheet)\nconst title = document.querySelector('h1');            // first match or null\nconst cards = document.querySelectorAll('.card');       // NodeList of all matches\nconst form = document.getElementById('order');\n\n// Read and change content\ntitle.textContent = 'New title';        // text only (safe)\ntitle.innerHTML = 'New <em>title</em>'; // parses HTML (never with user input)\n\n// Attributes, classes, styles, data\nconst img = document.querySelector('img');\nimg.src = 'new.jpg';\nimg.alt = 'A new picture';\nimg.getAttribute('src'); img.setAttribute('loading', 'lazy'); img.removeAttribute('width');\ntitle.classList.add('big'); title.classList.remove('big'); title.classList.toggle('open'); title.classList.contains('big');\ntitle.style.color = 'red';              // inline style (prefer toggling classes)\ntitle.dataset.id                        // reads data-id=\"...\"\n\n// Create, insert, remove\nconst li = document.createElement('li');\nli.textContent = 'New item';\ndocument.querySelector('ul').append(li);      // at the end (prepend for start)\ntitle.insertAdjacentHTML('afterend', '<p>Subtitle</p>');\nli.remove();\n\n// Move around the tree\nli.parentElement; li.children; li.nextElementSibling; li.closest('section');\n\n// Loop over a NodeList\ncards.forEach(card => card.classList.add('ready'));"),
    ("h2", "11. Events"),
    ("code", "const button = document.querySelector('#buy');\nbutton.addEventListener('click', (event) => {\n  event.preventDefault();          // stop the default action (e.g. following a link)\n  console.log(event.target);       // the element that was clicked\n  button.textContent = 'Added!';\n});\n\n// Common events\n// click, dblclick, input (every keystroke), change (after leaving a field), submit (form),\n// keydown/keyup, focus/blur, mouseenter/mouseleave, scroll, resize, load, DOMContentLoaded\n\n// Event delegation: one listener on the parent handles many children\ndocument.querySelector('ul').addEventListener('click', e => {\n  const li = e.target.closest('li');\n  if (li) li.classList.toggle('done');\n});\n\n// Keyboard\ndocument.addEventListener('keydown', e => { if (e.key === 'Escape') closeMenu(); });\n\n// Remove a listener (needs the same function reference)\nfunction onScroll() { /* ... */ }\nwindow.addEventListener('scroll', onScroll);\nwindow.removeEventListener('scroll', onScroll);"),
    ("h2", "12. Forms"),
    ("code", "const form = document.querySelector('form');\nform.addEventListener('submit', e => {\n  e.preventDefault();                          // handle it ourselves\n  if (!form.checkValidity()) {                 // built-in HTML validation\n    form.reportValidity();                     // show the browser messages\n    return;\n  }\n  const data = new FormData(form);             // all fields\n  const order = Object.fromEntries(data);      // { name: '...', email: '...' }\n  console.log(order.email);\n  form.reset();\n});\n\n// Individual controls\nconst qty = form.elements.qty;      // by name attribute\nqty.value                           // always a string; Number(qty.value) for maths\nqty.valueAsNumber                   // for number/date inputs\ncheckbox.checked                    // true/false\nselect.value; select.selectedIndex;\ninput.setCustomValidity('Please use your work email');  // custom error ('' clears it)\ninput.addEventListener('input', () => counter.textContent = input.value.length);"),
    ("h2", "13. Timers, dates and randomness"),
    ("code", "setTimeout(() => console.log('after 1 second'), 1000);\nconst id = setInterval(tick, 1000);   // every second\nclearInterval(id);\n\nconst now = new Date();\nnow.getFullYear(); now.getMonth() /* 0-11 */; now.getDate(); now.getDay() /* 0=Sunday */; now.getHours();\nnow.toLocaleDateString('en-GB')            // '11/09/2026'\nnow.toLocaleDateString('ar-EG', { dateStyle: 'long' })\nnew Date('2026-12-31') - now               // milliseconds until then\n\nMath.round(2.5); Math.floor(2.9); Math.ceil(2.1); Math.max(1, 5); Math.min(1, 5); Math.abs(-3);\nMath.random()                              // 0 to 1\nMath.floor(Math.random() * 6) + 1          // dice 1-6"),
    ("h2", "14. Storing data in the browser"),
    ("code", "localStorage.setItem('theme', 'dark');          // stays after closing the browser\nlocalStorage.getItem('theme')                   // 'dark' or null\nlocalStorage.removeItem('theme');\nsessionStorage.setItem('step', '2');            // cleared when the tab closes\n\n// Objects must be converted to text\nlocalStorage.setItem('cart', JSON.stringify(cart));\nconst cart = JSON.parse(localStorage.getItem('cart')) ?? [];"),
    ("h2", "15. Fetching data (AJAX) and promises"),
    ("code", "// fetch returns a Promise: a value that arrives later\nfetch('https://api.example.com/books')\n  .then(response => response.json())\n  .then(books => render(books))\n  .catch(error => console.error('Failed:', error));\n\n// Same with async/await (easier to read)\nasync function loadBooks() {\n  try {\n    const response = await fetch('/data/books.json');\n    if (!response.ok) throw new Error('HTTP ' + response.status);\n    const books = await response.json();\n    render(books);\n  } catch (error) {\n    showMessage('Could not load books.');\n  }\n}\n\n// Sending data\nawait fetch('/api/orders', {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ book: 'Learn HTML', qty: 1 })\n});"),
    ("p", "When you open an HTML file directly from your disk (file://), fetch to local files is blocked by browsers. Use a tiny local server "
          "(for example the Live Server extension, or python -m http.server in the folder) and open http://localhost:8000."),
    ("h2", "16. Errors and debugging"),
    ("code", "try {\n  JSON.parse('not json');\n} catch (error) {\n  console.error(error.message);   // 'Unexpected token ...'\n} finally {\n  console.log('always runs');\n}\nthrow new Error('Quantity must be positive');\n\nconsole.log('value:', value);   // print\nconsole.table(books);           // arrays of objects as a table\nconsole.dir(element);           // object view of a DOM node\ndebugger;                       // pauses in DevTools Sources panel"),
    ("table", [["Error message", "Usual cause"], ["Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')", "querySelector found nothing: wrong selector, or script ran before the element existed (add defer)"],
               ["Uncaught ReferenceError: x is not defined", "Typo in a name, or the variable is declared in another scope / later"],
               ["Uncaught SyntaxError: Unexpected token", "Missing bracket, quote or comma; check the line number"],
               ["Failed to fetch / CORS", "Server does not allow requests from your origin, or you opened the page as file://"],
               ["NaN in the output", "Maths on a string; convert with Number() first"]]),
    ("h2", "17. Modules and organising code"),
    ("code", "// utils.js\nexport function formatPrice(n) { return n.toLocaleString('en-EG') + ' EGP'; }\nexport const TAX = 0.14;\n\n// main.js  (loaded with <script type=\"module\" src=\"main.js\">)\nimport { formatPrice, TAX } from './utils.js';\nconsole.log(formatPrice(120 * (1 + TAX)));"),
    ("h2", "18. Classes (optional)"),
    ("code", "class Cart {\n  #items = [];                       // private field\n  add(book, qty = 1) { this.#items.push({ book, qty }); return this; }\n  get total() { return this.#items.reduce((t, i) => t + i.book.price * i.qty, 0); }\n}\nconst cart = new Cart();\ncart.add({ title: 'Learn HTML', price: 120 }, 2);\ncart.total   // 240"),
    ("h2", "19. Good habits"),
    ("ul", ["Use const by default, let when the value changes, never var.", "Use === and !==.", "Name things clearly: isOpen, totalPrice, renderCart().",
            "Keep functions small and single-purpose; keep DOM changes in a render function.", "Never put user input into innerHTML; use textContent or createElement.",
            "Progressive enhancement: the page should still work (or degrade gracefully) if JavaScript fails to load.",
            "Add keyboard support and ARIA state (aria-expanded, aria-selected) to every custom widget.", "Test in the console; read error messages; use breakpoints."]),
]

# (group, name, syntax, description, example)
JS_REFERENCE = [
    ("Variables and types", "let / const / var", "let x = 1; const y = 2;", "Declare variables. const cannot be reassigned; let can; var is legacy (function-scoped).", "const TAX = 0.14;\nlet total = 0;\ntotal += 100 * TAX;"),
    ("Variables and types", "typeof", "typeof value", "Returns the type name as a string.", "typeof 'a'   // 'string'\ntypeof 1     // 'number'"),
    ("Variables and types", "Number()", "Number(value)", "Converts to a number; NaN if impossible.", "Number('42')   // 42\nNumber('abc')  // NaN"),
    ("Variables and types", "parseInt() / parseFloat()", "parseInt(text, 10)", "Reads a leading integer / decimal from text.", "parseInt('12px', 10)  // 12\nparseFloat('3.5kg')   // 3.5"),
    ("Variables and types", "String()", "String(value)", "Converts to text.", "String(42)   // '42'"),
    ("Variables and types", "Boolean()", "Boolean(value)", "Converts to true/false using truthiness.", "Boolean('')   // false\nBoolean('0')  // true"),
    ("Variables and types", "isNaN() / Number.isNaN()", "Number.isNaN(x)", "Tests for NaN. Prefer Number.isNaN (no conversion).", "Number.isNaN(0 / 0)  // true"),
    ("Variables and types", "Array.isArray()", "Array.isArray(value)", "True if the value is an array.", "Array.isArray([1])  // true"),
    ("Strings", "length", "text.length", "Number of characters.", "'Cairo'.length  // 5"),
    ("Strings", "toUpperCase() / toLowerCase()", "text.toUpperCase()", "Change case.", "'abc'.toUpperCase()  // 'ABC'"),
    ("Strings", "includes()", "text.includes(part)", "True if part occurs in text.", "'Book Shop'.includes('Shop')  // true"),
    ("Strings", "startsWith() / endsWith()", "text.startsWith(part)", "Test the beginning / end.", "'index.html'.endsWith('.html')  // true"),
    ("Strings", "indexOf()", "text.indexOf(part)", "Position of the first occurrence or -1.", "'banana'.indexOf('n')  // 2"),
    ("Strings", "slice()", "text.slice(start, end)", "Copy part of a string (end not included; negatives from the end).", "'Cairo Book'.slice(0, 5)  // 'Cairo'"),
    ("Strings", "split()", "text.split(separator)", "Split into an array.", "'a,b,c'.split(',')  // ['a','b','c']"),
    ("Strings", "replace() / replaceAll()", "text.replace(old, new)", "Replace the first / every occurrence.", "'2026-09-11'.replaceAll('-', '/')"),
    ("Strings", "trim()", "text.trim()", "Remove spaces at both ends.", "'  hi '.trim()  // 'hi'"),
    ("Strings", "padStart() / padEnd()", "text.padStart(length, fill)", "Pad to a length.", "'7'.padStart(2, '0')  // '07'"),
    ("Strings", "Template literal", "`text ${expression}`", "String with embedded expressions and line breaks.", "`Hello ${name}, total ${qty * price} EGP`"),
    ("Strings", "toFixed()", "number.toFixed(digits)", "Format a number with fixed decimals (returns a string).", "(3.14159).toFixed(2)  // '3.14'"),
    ("Strings", "toLocaleString()", "number.toLocaleString(locale, options)", "Format numbers, currencies and dates for a locale.", "(1500).toLocaleString('en-EG', { style: 'currency', currency: 'EGP' })"),
    ("Arrays", "push() / pop()", "arr.push(item)", "Add to / remove from the end (changes the array).", "list.push('x');\nlist.pop();"),
    ("Arrays", "unshift() / shift()", "arr.unshift(item)", "Add to / remove from the start.", "queue.shift();"),
    ("Arrays", "indexOf() / includes()", "arr.includes(item)", "Find position / test presence.", "['a','b'].includes('b')  // true"),
    ("Arrays", "slice()", "arr.slice(start, end)", "Copy part of an array (original unchanged).", "[1,2,3,4].slice(1, 3)  // [2,3]"),
    ("Arrays", "splice()", "arr.splice(start, deleteCount, ...items)", "Remove and/or insert in place.", "list.splice(2, 1);  // remove index 2"),
    ("Arrays", "concat() / spread", "[...a, ...b]", "Join arrays into a new one.", "const all = [...first, ...second];"),
    ("Arrays", "join()", "arr.join(separator)", "Make a string.", "['a','b'].join(' - ')  // 'a - b'"),
    ("Arrays", "forEach()", "arr.forEach((item, index) => {})", "Run a function for each item.", "cards.forEach(c => c.hidden = false);"),
    ("Arrays", "map()", "arr.map(item => newItem)", "New array of transformed items.", "prices.map(p => p * 2)"),
    ("Arrays", "filter()", "arr.filter(item => condition)", "New array of items that pass.", "books.filter(b => b.price < 150)"),
    ("Arrays", "reduce()", "arr.reduce((acc, item) => acc, start)", "Combine into one value.", "prices.reduce((s, p) => s + p, 0)"),
    ("Arrays", "find() / findIndex()", "arr.find(item => condition)", "First matching item / its index.", "books.find(b => b.id === 3)"),
    ("Arrays", "some() / every()", "arr.some(item => condition)", "Any / all items pass.", "cart.every(i => i.qty > 0)"),
    ("Arrays", "sort()", "arr.sort((a, b) => a - b)", "Sort in place. Without a compare function items are sorted as text.", "[10, 9, 1].sort((a, b) => a - b)  // [1, 9, 10]"),
    ("Arrays", "reverse()", "arr.reverse()", "Reverse in place (toReversed() for a copy).", "[1,2,3].toReversed()  // [3,2,1]"),
    ("Arrays", "flat() / flatMap()", "arr.flat(depth)", "Flatten nested arrays.", "[[1],[2,3]].flat()  // [1,2,3]"),
    ("Arrays", "Array.from()", "Array.from(iterable, mapFn)", "Make a real array from a NodeList, string or length.", "Array.from({ length: 5 }, (_, i) => i + 1)  // [1..5]"),
    ("Objects", "Object.keys() / values() / entries()", "Object.keys(obj)", "Arrays of keys / values / [key, value] pairs.", "Object.entries(prices).forEach(([k, v]) => ...)"),
    ("Objects", "Object.assign() / spread", "{ ...obj, key: value }", "Shallow copy and merge.", "const settings = { ...defaults, ...userPrefs };"),
    ("Objects", "Object.fromEntries()", "Object.fromEntries(pairs)", "Build an object from pairs (e.g. FormData).", "Object.fromEntries(new FormData(form))"),
    ("Objects", "Destructuring", "const { a, b = 2 } = obj; const [x, y] = arr;", "Pull values into variables.", "const { title, price = 0 } = book;"),
    ("Objects", "Optional chaining ?.", "obj?.prop?.deep", "Returns undefined instead of throwing when something is null.", "user?.address?.city"),
    ("Objects", "JSON.stringify() / JSON.parse()", "JSON.stringify(obj)", "Convert between objects and JSON text.", "localStorage.setItem('cart', JSON.stringify(cart));"),
    ("Objects", "structuredClone()", "structuredClone(obj)", "Deep copy of plain data.", "const backup = structuredClone(state);"),
    ("Functions", "function declaration", "function name(params) { return value; }", "Named, hoisted function.", "function area(w, h) { return w * h; }"),
    ("Functions", "arrow function", "(params) => expression", "Short function; no own this; implicit return without braces.", "const double = n => n * 2;"),
    ("Functions", "default and rest parameters", "function f(a = 1, ...rest) {}", "Defaults for missing arguments; rest collects extras.", "function log(level = 'info', ...msgs) {}"),
    ("Functions", "callback", "doSomething(function () {})", "A function passed to another function to be called later.", "button.addEventListener('click', handleClick);"),
    ("Functions", "closure", "function outer() { let n = 0; return () => ++n; }", "Inner function remembers outer variables.", "const next = counter(); next(); next(); // 2"),
    ("Functions", "IIFE", "(() => { ... })();", "Run a function immediately; keeps variables private.", "(() => { const secret = 1; })();"),
    ("Control flow", "if / else if / else", "if (c) {} else if (d) {} else {}", "Branching.", "if (qty > 10) discount = 0.1;"),
    ("Control flow", "switch", "switch (v) { case 1: ...; break; default: ... }", "Multi-way branch on one value.", "switch (status) { case 'paid': ... }"),
    ("Control flow", "ternary ? :", "condition ? a : b", "Expression form of if/else.", "const label = n === 1 ? 'item' : 'items';"),
    ("Control flow", "for", "for (let i = 0; i < n; i++) {}", "Counted loop.", "for (let i = 1; i <= 10; i++) rows += `<tr><td>${i}</td></tr>`;"),
    ("Control flow", "for...of", "for (const item of iterable) {}", "Loop over values of arrays, strings, NodeLists, Maps.", "for (const li of list.children) li.hidden = true;"),
    ("Control flow", "for...in", "for (const key in obj) {}", "Loop over keys of an object.", "for (const k in prices) total += prices[k];"),
    ("Control flow", "while / do...while", "while (c) {}", "Loop while a condition holds.", "while (i < 3) i++;"),
    ("Control flow", "break / continue", "break; continue;", "Leave the loop / skip to next turn.", "if (!item) continue;"),
    ("Control flow", "try / catch / finally / throw", "try {} catch (e) {} finally {}", "Handle errors.", "try { parse() } catch (e) { alert(e.message) }"),
    ("DOM: selecting", "document.querySelector()", "document.querySelector(cssSelector)", "First matching element or null.", "const nav = document.querySelector('nav.main');"),
    ("DOM: selecting", "document.querySelectorAll()", "document.querySelectorAll(cssSelector)", "Static NodeList of all matches (forEach works).", "document.querySelectorAll('.card').forEach(...)"),
    ("DOM: selecting", "getElementById()", "document.getElementById(id)", "Element by id (fast).", "document.getElementById('total')"),
    ("DOM: selecting", "closest()", "element.closest(selector)", "Nearest ancestor (or self) matching the selector.", "e.target.closest('li')"),
    ("DOM: selecting", "matches()", "element.matches(selector)", "True if the element matches.", "if (el.matches('.active')) ..."),
    ("DOM: selecting", "parentElement / children / nextElementSibling / previousElementSibling / firstElementChild", "element.children", "Navigate the tree.", "li.parentElement.remove();"),
    ("DOM: content", "textContent", "element.textContent = text", "Read/set text (safe; no HTML parsing).", "price.textContent = total + ' EGP';"),
    ("DOM: content", "innerHTML", "element.innerHTML = html", "Read/set HTML inside. Never use with untrusted input.", "list.innerHTML = items.map(i => `<li>${i}</li>`).join('');"),
    ("DOM: content", "createElement() / append() / prepend() / before() / after()", "parent.append(child)", "Create and insert nodes.", "const li = document.createElement('li'); ul.append(li);"),
    ("DOM: content", "insertAdjacentHTML()", "el.insertAdjacentHTML('beforeend', html)", "Insert HTML at a position: beforebegin, afterbegin, beforeend, afterend.", "list.insertAdjacentHTML('beforeend', '<li>New</li>');"),
    ("DOM: content", "remove() / replaceWith() / cloneNode()", "element.remove()", "Remove, replace or copy nodes.", "const copy = card.cloneNode(true);"),
    ("DOM: content", "<template> content", "template.content.cloneNode(true)", "Stamp out reusable HTML fragments.", "const row = tpl.content.cloneNode(true); tbody.append(row);"),
    ("DOM: attributes and classes", "getAttribute() / setAttribute() / removeAttribute() / hasAttribute()", "el.setAttribute(name, value)", "Work with any attribute.", "link.setAttribute('aria-current', 'page');"),
    ("DOM: attributes and classes", "classList", "el.classList.add('x') / remove / toggle / contains / replace", "Manage classes without string juggling.", "menu.classList.toggle('open');"),
    ("DOM: attributes and classes", "dataset", "el.dataset.name", "Read/write data-* attributes (data-user-id becomes dataset.userId).", "const id = button.dataset.id;"),
    ("DOM: attributes and classes", "style", "el.style.property = value", "Inline styles (camelCase: backgroundColor).", "bar.style.width = percent + '%';"),
    ("DOM: attributes and classes", "hidden / disabled / checked / value", "el.hidden = true", "Direct properties for common attributes.", "submit.disabled = !form.checkValidity();"),
    ("DOM: attributes and classes", "getComputedStyle()", "getComputedStyle(el).property", "Read the final CSS value.", "getComputedStyle(box).width"),
    ("DOM: size and scroll", "getBoundingClientRect()", "el.getBoundingClientRect()", "Position and size relative to the viewport.", "const { top, height } = el.getBoundingClientRect();"),
    ("DOM: size and scroll", "scrollIntoView()", "el.scrollIntoView({ behavior: 'smooth' })", "Scroll the element into view.", "section.scrollIntoView({ behavior: 'smooth', block: 'start' });"),
    ("DOM: size and scroll", "window.scrollTo() / scrollY / innerWidth", "window.scrollTo({ top: 0 })", "Scroll the page; read scroll position and viewport size.", "if (window.scrollY > 300) topBtn.hidden = false;"),
    ("DOM: size and scroll", "IntersectionObserver", "new IntersectionObserver(callback, options).observe(el)", "Run code when an element enters the viewport (lazy effects, infinite scroll).", "io.observe(document.querySelector('.reveal'));"),
    ("Events", "addEventListener()", "el.addEventListener(type, handler, options)", "Attach a handler; several per event are allowed.", "btn.addEventListener('click', onClick, { once: true });"),
    ("Events", "removeEventListener()", "el.removeEventListener(type, handler)", "Detach a handler (same function reference).", "window.removeEventListener('resize', onResize);"),
    ("Events", "event.target / currentTarget", "e.target", "Element that triggered the event / element the listener is on.", "const row = e.target.closest('tr');"),
    ("Events", "event.preventDefault()", "e.preventDefault()", "Cancel the default action (submit, follow link, type character).", "form.addEventListener('submit', e => { e.preventDefault(); ... });"),
    ("Events", "event.stopPropagation()", "e.stopPropagation()", "Stop the event bubbling to ancestors.", "menu.addEventListener('click', e => e.stopPropagation());"),
    ("Events", "click / dblclick / contextmenu", "'click'", "Mouse or keyboard activation of buttons and links.", "btn.addEventListener('click', ...)"),
    ("Events", "input / change", "'input'", "input fires on every change while typing; change when the value is committed.", "search.addEventListener('input', filterList);"),
    ("Events", "submit / reset", "'submit'", "Form submission (fires on the form, not the button).", "form.addEventListener('submit', ...)"),
    ("Events", "keydown / keyup", "'keydown'", "Keyboard; e.key gives the key name ('Enter', 'Escape', 'a').", "if (e.key === 'Enter') save();"),
    ("Events", "focus / blur / focusin / focusout", "'focus'", "Element gains / loses focus (focusin/focusout bubble).", "input.addEventListener('blur', validate);"),
    ("Events", "mouseenter / mouseleave / mousemove / pointerdown", "'pointerdown'", "Pointer movement; pointer events cover mouse, touch and pen.", "card.addEventListener('mouseenter', preview);"),
    ("Events", "scroll / resize", "'scroll'", "Page or element scrolled; window resized. Throttle heavy work.", "window.addEventListener('scroll', onScroll, { passive: true });"),
    ("Events", "DOMContentLoaded / load", "'DOMContentLoaded'", "HTML parsed / everything (images) loaded. Unnecessary when using defer.", "document.addEventListener('DOMContentLoaded', init);"),
    ("Events", "toggle (details) / close (dialog) / animationend / transitionend", "'toggle'", "Widget and animation lifecycle events.", "details.addEventListener('toggle', ...)"),
    ("Events", "CustomEvent / dispatchEvent", "el.dispatchEvent(new CustomEvent('cart:add', { detail, bubbles: true }))", "Create your own events between components.", "document.addEventListener('cart:add', e => update(e.detail));"),
    ("Forms", "form.elements", "form.elements.fieldName", "Access controls by name or id.", "form.elements.email.value"),
    ("Forms", "FormData", "new FormData(form)", "Collect all field values; works with fetch.", "const data = Object.fromEntries(new FormData(form));"),
    ("Forms", "checkValidity() / reportValidity()", "form.checkValidity()", "Run HTML validation; report shows the messages.", "if (!form.reportValidity()) return;"),
    ("Forms", "setCustomValidity()", "input.setCustomValidity(message)", "Custom error message ('' means valid).", "pass2.setCustomValidity(pass1.value === pass2.value ? '' : 'Passwords differ');"),
    ("Forms", "validity", "input.validity.valueMissing / typeMismatch / patternMismatch / tooShort / rangeUnderflow", "Which rule failed.", "if (email.validity.typeMismatch) msg = 'Enter a valid email';"),
    ("Forms", "value / valueAsNumber / valueAsDate / checked / files", "input.valueAsNumber", "Typed access to control values.", "const qty = qtyInput.valueAsNumber || 1;"),
    ("Forms", "select.options / selectedIndex / selectedOptions", "select.value", "Work with drop-downs.", "[...select.selectedOptions].map(o => o.value)"),
    ("Forms", "form.submit() / requestSubmit() / reset()", "form.requestSubmit()", "Submit programmatically (requestSubmit runs validation and the submit event).", "form.requestSubmit();"),
    ("Browser APIs", "localStorage / sessionStorage", "localStorage.setItem(key, text)", "Persist small text values per site.", "localStorage.getItem('theme') ?? 'light'"),
    ("Browser APIs", "fetch()", "await fetch(url, options)", "HTTP requests; returns a Response (json(), text()).", "const data = await (await fetch('/api/books')).json();"),
    ("Browser APIs", "Promise / async / await", "async function f() { await p; }", "Work with values that arrive later.", "const [a, b] = await Promise.all([fetch(u1), fetch(u2)]);"),
    ("Browser APIs", "setTimeout() / setInterval() / clearTimeout() / requestAnimationFrame()", "setTimeout(fn, ms)", "Run later / repeatedly / next frame.", "const t = setTimeout(hide, 3000); clearTimeout(t);"),
    ("Browser APIs", "Date", "new Date(); new Date('2026-09-11')", "Dates and times; months are 0-based.", "new Date().toLocaleDateString('ar-EG')"),
    ("Browser APIs", "Intl.NumberFormat / Intl.DateTimeFormat", "new Intl.NumberFormat('en-EG', { style: 'currency', currency: 'EGP' }).format(n)", "Locale-aware formatting.", "fmt.format(1250)  // 'EGP 1,250.00'"),
    ("Browser APIs", "location / history", "location.href; history.pushState()", "Current URL; navigate; manage back button.", "location.hash = '#prices';"),
    ("Browser APIs", "URL / URLSearchParams", "new URL(location).searchParams.get('page')", "Parse and build URLs and query strings.", "const page = new URLSearchParams(location.search).get('page') ?? '1';"),
    ("Browser APIs", "navigator", "navigator.language; navigator.clipboard.writeText(text); navigator.share()", "Browser and device information and capabilities.", "await navigator.clipboard.writeText(code);"),
    ("Browser APIs", "matchMedia()", "matchMedia('(prefers-color-scheme: dark)').matches", "Test media queries in JavaScript and listen for changes.", "mq.addEventListener('change', applyTheme);"),
    ("Browser APIs", "dialog.showModal() / close() / popover APIs", "dialog.showModal()", "Open native dialogs and popovers.", "el.showPopover(); el.hidePopover(); el.togglePopover();"),
    ("Browser APIs", "alert() / confirm() / prompt()", "confirm('Delete?')", "Simple blocking dialogs (avoid in real products).", "if (confirm('Remove item?')) remove();"),
    ("Browser APIs", "console", "console.log / table / error / warn / group / time", "Debug output.", "console.table(cart);"),
    ("Browser APIs", "JSON files with fetch", "await (await fetch('data.json')).json()", "Load content from a local JSON file (needs a local server).", "const books = await (await fetch('books.json')).json();"),
    ("Browser APIs", "Web Storage vs cookies", "document.cookie", "Cookies go to the server on each request; storage stays in the browser.", "document.cookie = 'lang=ar; max-age=31536000; path=/';"),
    ("Browser APIs", "Geolocation / Notification / Web Share (permission APIs)", "navigator.geolocation.getCurrentPosition(cb)", "Need user permission; provide fallbacks.", "navigator.geolocation.getCurrentPosition(p => show(p.coords));"),
]

JS_COURSE = [
("Lesson 37: JavaScript - your first script", [
    ("p", "Create app.js next to index.html, link it with <script src=\"app.js\" defer></script> in the head, and write:"),
    ("code", "console.log('The page is ready');\nconst heading = document.querySelector('h1');\nheading.textContent = 'Hello from JavaScript';\nheading.style.color = 'darkred';"),
    ("ul", ["Open the page, press F12 and look at the Console tab: the message appears and the heading changed.",
            "Change the text, save, reload. This edit-save-reload loop is how you will learn.",
            "Break it on purpose: misspell querySelector. Read the red error: it tells you the file and line."]),
    ("h3", "Where scripts run"),
    ("table", [["Placement", "Behaviour"], ["<script src> in head without defer", "Runs immediately; elements below do not exist yet (querySelector returns null)"],
               ["<script src defer> in head", "Downloads in parallel, runs after the HTML is parsed - recommended"], ["<script> at end of body", "Runs after the elements above it exist"],
               ["<script type=module>", "Deferred automatically, strict mode, supports import/export"]]),
]),
("Lesson 38: Variables, types and operators", [
    ("code", "const shop = 'Cairo Book Shop';   // string\nlet booksSold = 0;                  // number\nconst isOpen = true;                // boolean\nlet discount;                       // undefined\nconst prices = [120, 150, 180];     // array\nconst owner = { name: 'Mohamed', city: 'Giza' };  // object\n\nbooksSold = booksSold + 3;\nconst total = prices[0] + prices[1];      // 270\nconst message = `${shop}: ${booksSold} sold, total ${total} EGP`;\nconsole.log(message);\nconsole.log(typeof total, typeof message);"),
    ("ul", ["const for values that never change reference; let for counters and state.", "Strings and numbers do not mix silently the way you might expect: '5' + 1 is '51' but '5' - 1 is 4. Convert with Number().",
            "Compare with === (same type and value)."]),
    ("h3", "Exercise"),
    ("p", "Store your four offers as an array of objects with title and price; print the total price and the cheapest title in the console."),
]),
("Lesson 39: Conditions and loops", [
    ("code", "const hour = new Date().getHours();\nlet status;\nif (hour >= 10 && hour < 22) {\n  status = 'Open now';\n} else {\n  status = 'Closed';\n}\ndocument.querySelector('#status').textContent = status;\n\nconst prices = [120, 150, 180, 95];\nlet total = 0;\nfor (const p of prices) total += p;\n\nlet rows = '';\nfor (let i = 0; i < prices.length; i++) {\n  rows += `<tr><td>Book ${i + 1}</td><td>${prices[i]} EGP</td></tr>`;\n}\ndocument.querySelector('tbody').innerHTML = rows;"),
    ("ul", ["for...of for values, for...in for object keys, classic for when you need the index.",
            "Build strings in a loop and insert once with innerHTML (faster than touching the DOM each turn) - but only with your own data, never user input."]),
]),
("Lesson 40: Functions", [
    ("code", "function formatPrice(amount, currency = 'EGP') {\n  return `${amount.toLocaleString('en-EG')} ${currency}`;\n}\n\nconst withDiscount = (price, percent) => price * (1 - percent / 100);\n\nfunction renderTotal(items) {\n  const total = items.reduce((sum, item) => sum + item.price * item.qty, 0);\n  document.querySelector('#total').textContent = formatPrice(total);\n}\n\nrenderTotal([{ price: 120, qty: 2 }, { price: 150, qty: 1 }]);   // 390 EGP"),
    ("ul", ["One job per function; name it with a verb: renderTotal, formatPrice, validateEmail.", "Return values instead of printing inside; the caller decides what to do.",
            "Keep DOM updates in render functions so the data logic is testable in the console."]),
]),
("Lesson 41: Arrays and objects in practice", [
    ("code", "const books = [\n  { id: 1, title: 'Learn HTML', price: 120, tags: ['html', 'beginner'] },\n  { id: 2, title: 'CSS in Practice', price: 150, tags: ['css'] },\n  { id: 3, title: 'JavaScript Basics', price: 180, tags: ['js', 'beginner'] },\n];\n\nconst cheap = books.filter(b => b.price < 160);\nconst titles = books.map(b => b.title);\nconst byPrice = [...books].sort((a, b) => a.price - b.price);\nconst beginner = books.filter(b => b.tags.includes('beginner'));\nconst total = books.reduce((s, b) => s + b.price, 0);\nconst js = books.find(b => b.id === 3);\nconst { title, price } = js;\n\nconsole.table(byPrice);\nlocalStorage.setItem('books', JSON.stringify(books));"),
    ("p", "Most page logic is: keep data in an array of objects, transform it with map/filter/sort, then render it. Practise these five methods until they feel natural."),
]),
("Lesson 42: The DOM - reading and changing the page", [
    ("code", "// HTML: <ul id=\"list\"></ul> <p id=\"count\"></p>\nconst list = document.querySelector('#list');\nconst count = document.querySelector('#count');\n\nfunction render(items) {\n  list.innerHTML = '';                       // clear\n  for (const item of items) {\n    const li = document.createElement('li');\n    li.textContent = item.title;             // safe for any text\n    li.dataset.id = item.id;\n    if (item.price > 150) li.classList.add('premium');\n    list.append(li);\n  }\n  count.textContent = `${items.length} ${items.length === 1 ? 'book' : 'books'}`;\n}\nrender(books);"),
    ("ul", ["querySelector uses the same selectors as CSS.", "textContent for text; createElement + append for structure; innerHTML only for trusted markup.",
            "Toggle classes and let CSS do the styling instead of setting style properties one by one."]),
]),
("Lesson 43: Events - responding to the user", [
    ("code", "const form = document.querySelector('#add');\nconst input = form.elements.title;\n\nform.addEventListener('submit', e => {\n  e.preventDefault();\n  const title = input.value.trim();\n  if (!title) return;\n  books.push({ id: Date.now(), title, price: 0, tags: [] });\n  render(books);\n  form.reset();\n  input.focus();\n});\n\n// One listener for all items (event delegation)\nlist.addEventListener('click', e => {\n  const li = e.target.closest('li');\n  if (!li) return;\n  li.classList.toggle('selected');\n});\n\ndocument.addEventListener('keydown', e => {\n  if (e.key === 'Escape') list.querySelectorAll('.selected').forEach(li => li.classList.remove('selected'));\n});"),
    ("ul", ["Listen on the form's submit, not the button's click: Enter in a field then works too.", "Delegation keeps working for items added later.",
            "Always pair mouse interactions with keyboard equivalents."]),
]),
("Lesson 44: Forms and validation with JavaScript", [
    ("code", "const form = document.querySelector('#order');\nconst email = form.elements.email;\nconst error = document.querySelector('#email-error');\n\nemail.addEventListener('input', () => {\n  if (email.validity.typeMismatch) {\n    email.setCustomValidity('Please enter an address like name@example.com');\n  } else {\n    email.setCustomValidity('');\n  }\n  error.textContent = email.validationMessage;   // live message, also read by screen readers via aria-live\n});\n\nform.addEventListener('submit', async e => {\n  e.preventDefault();\n  if (!form.reportValidity()) return;\n  const data = Object.fromEntries(new FormData(form));\n  const button = form.querySelector('button');\n  button.disabled = true;\n  try {\n    const res = await fetch('/api/order', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });\n    if (!res.ok) throw new Error('Server error');\n    form.hidden = true;\n    document.querySelector('#thanks').hidden = false;\n  } catch (err) {\n    error.textContent = 'Could not send. Please try again.';\n  } finally {\n    button.disabled = false;\n  }\n});"),
    ("ul", ["Start from HTML validation (required, type, pattern) and add JavaScript only for custom rules.", "Show errors as text near the field inside an element with aria-live=\"polite\".",
            "Disable the button while sending to prevent double orders."]),
]),
("Lesson 45: Fetching data and storing state", [
    ("code", "// books.json  (served by a local server, e.g. python -m http.server)\n// [ { \"id\": 1, \"title\": \"Learn HTML\", \"price\": 120 }, ... ]\n\nasync function loadBooks() {\n  const cached = localStorage.getItem('books');\n  if (cached) return JSON.parse(cached);\n  const res = await fetch('books.json');\n  const books = await res.json();\n  localStorage.setItem('books', JSON.stringify(books));\n  return books;\n}\n\nloadBooks().then(render).catch(() => {\n  document.querySelector('#list').textContent = 'Could not load the catalogue.';\n});\n\n// Reading the query string: books.html?tag=css\nconst tag = new URLSearchParams(location.search).get('tag');\nif (tag) render(books.filter(b => b.tags.includes(tag)));"),
    ("ul", ["fetch + await + json() is the pattern for almost every data load.", "Always handle the failure path: show a message, not a blank page.",
            "localStorage stores strings only; JSON.stringify on the way in, JSON.parse on the way out."]),
]),
("Lesson 46: Building accessible interactive components", [
    ("code", "// Accessible disclosure button (menu, accordion, 'read more')\nconst button = document.querySelector('#menu-button');\nconst menu = document.querySelector('#menu');\n\nfunction setOpen(open) {\n  button.setAttribute('aria-expanded', String(open));\n  menu.hidden = !open;\n  if (open) menu.querySelector('a')?.focus();\n}\nbutton.addEventListener('click', () => setOpen(button.getAttribute('aria-expanded') !== 'true'));\ndocument.addEventListener('keydown', e => { if (e.key === 'Escape') { setOpen(false); button.focus(); } });\ndocument.addEventListener('click', e => { if (!menu.contains(e.target) && e.target !== button) setOpen(false); });"),
    ("table", [["Widget", "Native element first", "If custom: ARIA and keys"], ["Menu / accordion", "<details>, <button> + hidden", "aria-expanded, aria-controls; Escape closes"],
               ["Dialog", "<dialog> showModal()", "aria-labelledby; focus trap; Escape"], ["Tabs", "-", "role=tablist/tab/tabpanel, aria-selected, arrow keys"],
               ["Tooltip / popover", "popover attribute, title", "aria-describedby; show on focus too"], ["Live updates", "-", "aria-live=\"polite\" region for messages and counts"]]),
    ("ul", ["Prefer native elements; they are accessible for free.", "Every state you change visually must also be reflected in an attribute (aria-expanded, aria-selected, hidden).",
            "Manage focus: move it into dialogs and back to the trigger when they close.", "Test with the keyboard only, then with a screen reader."]),
]),
("Lesson 47: JavaScript project - interactive catalogue", [
    ("p", "Combine the lessons: a catalogue page that loads books from JSON, filters as you type, sorts by price, adds items to a cart stored in localStorage, and shows the total. The full code is in the projects that follow this lesson."),
    ("code", "// Outline of app.js\nconst state = { books: [], query: '', sort: 'title', cart: JSON.parse(localStorage.getItem('cart')) ?? [] };\n\nfunction visibleBooks() {\n  return state.books\n    .filter(b => b.title.toLowerCase().includes(state.query))\n    .sort((a, b) => state.sort === 'price' ? a.price - b.price : a.title.localeCompare(b.title));\n}\nfunction render() { renderList(visibleBooks()); renderCart(); }\nfunction save() { localStorage.setItem('cart', JSON.stringify(state.cart)); }\n\nsearch.addEventListener('input', e => { state.query = e.target.value.toLowerCase(); render(); });\nsortSelect.addEventListener('change', e => { state.sort = e.target.value; render(); });\nlist.addEventListener('click', e => {\n  const id = Number(e.target.closest('[data-id]')?.dataset.id);\n  if (e.target.matches('.add')) { state.cart.push(id); save(); render(); }\n});\n\nloadBooks().then(books => { state.books = books; render(); });"),
    ("ul", ["Keep one state object; every change updates state then calls render().", "Never store DOM-derived truth; the DOM is a view of the state.",
            "Add features one at a time and test each in the console."]),
]),
]
