# -*- coding: utf-8 -*-
"""CSS reference part: fundamentals, selectors, and a property reference."""

CSS_INTRO = [
    ("p", "CSS (Cascading Style Sheets) is the language that describes how HTML elements look: colours, "
          "fonts, spacing, size, position and layout. HTML says what something is; CSS says how it appears. "
          "The two are kept separate so that the same HTML can be shown in many ways (desktop, phone, print, "
          "dark mode) by changing only the CSS."),
    ("h2", "Three ways to add CSS"),
    ("table", [
        ["Method", "How", "When to use"],
        ["External style sheet", "<link rel=\"stylesheet\" href=\"style.css\"> in <head>; rules live in style.css",
         "Always, for real projects. One file styles every page and is cached by the browser."],
        ["Internal style sheet", "<style> ... </style> in <head>", "Small single-page demos, emails, or page-specific overrides."],
        ["Inline style", "style=\"color: red\" attribute on an element", "Quick tests and values set by JavaScript. Avoid for general styling."],
    ]),
    ("code", "/* style.css */\nbody   { font-family: Arial, sans-serif; margin: 0; }\nfooter { background: #222; color: #fff; text-align: center; padding: 20px; }"),
    ("h2", "Anatomy of a rule"),
    ("code", "selector {\n  property: value;   /* one declaration */\n  property: value;\n}\n\nfooter {\n  color: gray;\n  text-align: center;\n}"),
    ("ul", [
        "The selector chooses which elements the rule applies to.",
        "Each declaration is a property name, a colon, a value and a semicolon.",
        "Declarations are grouped in curly braces to form a rule (or rule set).",
        "Comments are written /* like this */ and may span lines.",
    ]),
    ("h2", "The cascade: which rule wins"),
    ("p", "When several rules apply to the same element and property, the browser decides in this order:"),
    ("ul", [
        "Origin and importance: author styles beat browser defaults; !important declarations beat normal ones "
        "(avoid !important; it makes styles hard to override).",
        "Specificity: inline style (1,0,0,0) beats id selectors (0,1,0,0), which beat class/attribute/pseudo-class "
        "selectors (0,0,1,0), which beat element/pseudo-element selectors (0,0,0,1). Count each part; the higher total wins.",
        "Source order: if specificity is equal, the rule that appears later wins.",
        "Layers (@layer) and scope (@scope) add further control in modern CSS.",
    ]),
    ("code", "p { color: black; }           /* specificity 0,0,0,1 */\n.note { color: blue; }        /* 0,0,1,0 - wins over p */\n#intro { color: green; }      /* 0,1,0,0 - wins over .note */\n<p id=\"intro\" class=\"note\" style=\"color: red\">  /* inline wins: red */"),
    ("h2", "Inheritance"),
    ("p", "Some properties are inherited by child elements automatically: color, font-family, font-size, "
          "line-height, text-align, visibility, and most text properties. Others are not: margin, padding, "
          "border, background, width, height, display, position. Any property can be forced with the keywords "
          "inherit, initial, unset and revert."),
    ("h2", "Units"),
    ("table", [
        ["Unit", "Meaning", "Typical use"],
        ["px", "CSS pixel (1/96 inch)", "Borders, small fixed sizes, media query breakpoints"],
        ["em", "Relative to the element's font size", "Padding and margin that scale with text"],
        ["rem", "Relative to the root (html) font size, 16px by default", "Font sizes, spacing - predictable and respects user settings"],
        ["%", "Relative to the parent's corresponding dimension", "Widths in fluid layouts"],
        ["vw / vh", "1% of the viewport width / height", "Full-screen sections, fluid type"],
        ["vmin / vmax / dvh / svh / lvh", "Viewport-relative variants", "Mobile-safe full-height layouts (dvh)"],
        ["ch", "Width of the '0' character", "Line length: max-width: 65ch"],
        ["fr", "Fraction of free space (grid only)", "grid-template-columns: 1fr 2fr"],
        ["deg, rad, turn", "Angles", "Rotations, gradients"],
        ["s, ms", "Time", "Transitions and animations"],
        ["pt, cm, mm, in", "Physical units", "Print style sheets"],
    ]),
    ("h2", "Colours"),
    ("table", [
        ["Notation", "Example", "Notes"],
        ["Named colour", "red, steelblue, transparent, currentColor", "148 names; see Part 9"],
        ["Hex", "#e60000, #e60000cc (with alpha), #f00 (short)", "Most common"],
        ["rgb()", "rgb(230 0 0), rgb(230 0 0 / 50%)", "Modern space-separated syntax; commas still work"],
        ["hsl()", "hsl(0 100% 45%)", "Hue 0-360, saturation, lightness; easy to adjust"],
        ["oklch() / oklab()", "oklch(60% 0.2 30)", "Perceptually uniform; wide-gamut colours"],
        ["color-mix()", "color-mix(in oklab, red 30%, white)", "Mixing colours"],
        ["System colours", "Canvas, CanvasText, LinkText, ButtonFace", "Follow the operating system theme"],
    ]),
    ("h2", "The box model"),
    ("p", "Every element is a rectangular box made of four layers, from inside out: content, padding, border "
          "and margin. Width and height set the content box by default; with box-sizing: border-box they include "
          "padding and border, which is far easier to reason about. Most projects begin with the reset "
          "*, *::before, *::after { box-sizing: border-box; }."),
    ("code", "+-------------------------------- margin (transparent) ---+\n|  +---------------------------- border -----------------+  |\n|  |  +------------------------ padding ---------------+  |  |\n|  |  |                                                |  |  |\n|  |  |                  content                       |  |  |\n|  |  |                                                |  |  |\n|  |  +------------------------------------------------+  |  |\n|  +------------------------------------------------------+  |\n+------------------------------------------------------------+"),
    ("p", "Vertical margins of adjacent blocks collapse into a single margin equal to the larger of the two. "
          "Padding and borders never collapse. Backgrounds cover the content and padding (and, by default, "
          "extend under the border)."),
    ("h2", "Display and layout modes"),
    ("table", [
        ["display value", "Behaviour"],
        ["block", "Starts on a new line, fills the available width, respects width/height. div, p, h1, section, footer..."],
        ["inline", "Flows within text, only as wide as its content, ignores width/height and vertical margins. span, a, em, strong..."],
        ["inline-block", "Flows within text but respects width, height and vertical margins/padding. img, button, input."],
        ["none", "Removed from rendering entirely (also from the accessibility tree)."],
        ["flex", "The element becomes a flex container; children are laid out in a row or column with powerful alignment and distribution."],
        ["grid", "The element becomes a grid container; children are placed in rows and columns defined by grid-template-*."],
        ["inline-flex / inline-grid", "As flex/grid, but the container itself flows inline."],
        ["table, table-row, table-cell...", "Table layout without table elements."],
        ["list-item", "Generates a bullet or number marker (li)."],
        ["contents", "The element's box disappears but its children remain."],
        ["flow-root", "A block that contains its floats (clears them) and starts a new formatting context."],
    ]),
    ("h2", "Positioning"),
    ("table", [
        ["position value", "Behaviour"],
        ["static", "Default. Normal flow; top/left/etc. have no effect."],
        ["relative", "Normal flow, then shifted by top/right/bottom/left; the original space is kept. Also creates a containing block for absolute children."],
        ["absolute", "Removed from the flow and placed relative to the nearest positioned ancestor (or the initial containing block)."],
        ["fixed", "Removed from the flow and placed relative to the viewport; stays put when scrolling."],
        ["sticky", "Behaves as relative until it reaches the threshold (top: 0), then sticks like fixed within its parent."],
    ]),
    ("h2", "Flexbox in one page"),
    ("code", ".row {\n  display: flex;              /* children become flex items in a row */\n  flex-direction: row;        /* or column, row-reverse, column-reverse */\n  flex-wrap: wrap;            /* allow items to wrap onto new lines */\n  justify-content: space-between; /* main-axis distribution: flex-start | center | flex-end | space-around | space-evenly */\n  align-items: center;        /* cross-axis alignment: stretch | flex-start | center | flex-end | baseline */\n  gap: 16px;                  /* space between items */\n}\n.row > .item {\n  flex: 1;                    /* shorthand for flex-grow flex-shrink flex-basis: 1 1 0 */\n  order: 0;                   /* visual order */\n  align-self: flex-end;       /* override align-items for one item */\n}"),
    ("h2", "Grid in one page"),
    ("code", ".layout {\n  display: grid;\n  grid-template-columns: 200px 1fr;          /* two columns */\n  grid-template-rows: auto 1fr auto;         /* header, content, footer */\n  grid-template-areas:\n    \"header header\"\n    \"nav    main\"\n    \"footer footer\";\n  gap: 16px;\n  min-height: 100vh;\n}\nheader { grid-area: header; }\nnav    { grid-area: nav; }\nmain   { grid-area: main; }\nfooter { grid-area: footer; }\n\n/* Responsive cards without media queries */\n.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 24px; }"),
    ("h2", "Responsive design"),
    ("code", "/* Mobile first: base styles for small screens, then enhance */\n.container { padding: 16px; }\n\n@media (min-width: 600px) {\n  .container { padding: 32px; }\n}\n@media (min-width: 1024px) {\n  .container { max-width: 1180px; margin: 0 auto; }\n}\n\n/* Container queries: respond to the parent's size */\n.card-wrapper { container-type: inline-size; }\n@container (min-width: 400px) {\n  .card { display: flex; }\n}\n\n/* User preferences */\n@media (prefers-color-scheme: dark) { body { background: #111; color: #eee; } }\n@media (prefers-reduced-motion: reduce) { * { animation: none !important; transition: none !important; } }\n\n/* Print */\n@media print { nav, footer, .no-print { display: none; } }"),
    ("h2", "Custom properties (CSS variables)"),
    ("code", ":root {\n  --brand: #e60000;\n  --radius: 12px;\n  --font: \"Segoe UI\", Tahoma, Arial, sans-serif;\n}\n.btn {\n  background: var(--brand);\n  border-radius: var(--radius);\n  font-family: var(--font);\n}\n.btn.secondary { --brand: #555; }   /* override locally */"),
    ("h2", "Transitions and animations"),
    ("code", ".btn { transition: background-color 0.2s ease, transform 0.2s ease; }\n.btn:hover { background-color: #b90000; transform: translateY(-2px); }\n\n@keyframes fade-in {\n  from { opacity: 0; transform: translateY(8px); }\n  to   { opacity: 1; transform: none; }\n}\n.card { animation: fade-in 0.4s ease-out both; }"),
]

# Selectors: (selector, meaning, example)
CSS_SELECTORS = [
    ("*", "Universal selector: every element.", "* { box-sizing: border-box; }"),
    ("element", "Type selector: all elements with that tag name.", "p { line-height: 1.6; }"),
    (".class", "Class selector: elements with that class.", ".card { border: 1px solid #ccc; }"),
    ("#id", "ID selector: the one element with that id.", "#main { max-width: 960px; }"),
    ("[attr]", "Attribute present.", "input[required] { border-left: 3px solid red; }"),
    ("[attr=\"value\"]", "Attribute equals value.", "input[type=\"checkbox\"] { accent-color: green; }"),
    ("[attr~=\"word\"]", "Attribute contains the word in a space-separated list.", "[class~=\"featured\"] { ... }"),
    ("[attr|=\"en\"]", "Attribute equals en or starts with en-.", "[lang|=\"en\"] { quotes: '\u201c' '\u201d'; }"),
    ("[attr^=\"https\"]", "Attribute starts with.", "a[href^=\"https\"]::after { content: ' \u2197'; }"),
    ("[attr$=\".pdf\"]", "Attribute ends with.", "a[href$=\".pdf\"] { background: url(pdf.svg) no-repeat left; }"),
    ("[attr*=\"example\"]", "Attribute contains substring.", "a[href*=\"example.com\"] { color: green; }"),
    ("[attr=\"v\" i]", "Case-insensitive match.", "[type=\"TEXT\" i] { ... }"),
    ("A B", "Descendant combinator: B anywhere inside A.", "nav a { text-decoration: none; }"),
    ("A > B", "Child combinator: B directly inside A.", "ul > li { list-style: square; }"),
    ("A + B", "Adjacent sibling: B immediately after A.", "h2 + p { margin-top: 0; }"),
    ("A ~ B", "General sibling: any B after A with the same parent.", "h2 ~ p { color: #444; }"),
    ("A, B", "Selector list: either.", "h1, h2, h3 { font-family: Georgia, serif; }"),
    (":hover", "Pointer is over the element.", "a:hover { text-decoration: underline; }"),
    (":focus / :focus-visible / :focus-within", "Element has focus / focus shown by keyboard / a descendant has focus.", "button:focus-visible { outline: 3px solid #1b6fd8; }"),
    (":active", "Being clicked.", "button:active { transform: scale(0.98); }"),
    (":visited / :link", "Visited / unvisited link.", "a:visited { color: purple; }"),
    (":first-child / :last-child / :only-child", "Position among siblings.", "li:first-child { font-weight: bold; }"),
    (":nth-child(an+b) / :nth-last-child()", "Position formula: 2n (even), 2n+1 (odd), 3, -n+3 (first three).", "tr:nth-child(even) { background: #f7f7f7; }"),
    (":first-of-type / :last-of-type / :nth-of-type()", "Position among siblings of the same type.", "p:first-of-type { font-size: 1.1em; }"),
    (":not(selector)", "Negation.", "input:not([type=\"submit\"]) { width: 100%; }"),
    (":is(a, b) / :where(a, b)", "Matches any of the list; :where has zero specificity.", ":is(h1, h2, h3) a { color: inherit; }"),
    (":has(selector)", "Parent selector: element that contains a match.", "article:has(img) { display: grid; }\nlabel:has(input:invalid) { color: red; }"),
    (":empty", "No children (not even text).", "p:empty { display: none; }"),
    (":root", "The <html> element.", ":root { --gap: 16px; }"),
    (":checked / :indeterminate", "Checked checkbox/radio/option.", "input:checked + label { font-weight: bold; }"),
    (":disabled / :enabled / :read-only / :read-write", "Form control state.", "button:disabled { opacity: 0.5; }"),
    (":required / :optional", "Form control requirement.", "input:required { border-color: #999; }"),
    (":valid / :invalid / :user-invalid / :in-range / :out-of-range / :placeholder-shown", "Validation state.", "input:user-invalid { border-color: red; }"),
    (":target", "Element whose id matches the URL fragment.", ":target { background: #fff9c4; }"),
    (":lang(ar)", "Element language.", ":lang(ar) { font-family: Cairo, sans-serif; }"),
    (":dir(rtl)", "Text direction.", ":dir(rtl) .icon { transform: scaleX(-1); }"),
    (":popover-open / :modal / :fullscreen / :open", "Top-layer and open states.", "dialog:modal { border-radius: 12px; }"),
    ("::before / ::after", "Generated content before/after the element's content (needs content property).", "q::before { content: open-quote; }"),
    ("::first-line / ::first-letter", "First line / first letter of a block.", "p::first-letter { font-size: 2em; float: left; }"),
    ("::marker", "List bullet or number.", "li::marker { color: red; }"),
    ("::placeholder", "Placeholder text in inputs.", "input::placeholder { color: #999; }"),
    ("::selection", "Text selected by the user.", "::selection { background: #ffd166; }"),
    ("::backdrop", "The backdrop behind a modal dialog, popover or fullscreen element.", "dialog::backdrop { background: rgb(0 0 0 / 0.6); }"),
    ("::part(name) / ::slotted(sel)", "Shadow DOM parts and slotted content.", "my-el::part(label) { color: red; }"),
    ("::file-selector-button", "The button in a file input.", "input::file-selector-button { padding: 8px; }"),
    ("::cue", "WebVTT captions in video.", "video::cue { background: rgb(0 0 0 / 0.8); }"),
]

# Properties: (group, property, values, description, example)
CSS_PROPERTIES = [
    # Text and fonts
    ("Fonts and text", "font-family", "family names and generic family",
     "The typeface used for text. Give a comma-separated list, most preferred first, ending with a generic family (serif, sans-serif, monospace, cursive, fantasy, system-ui, ui-monospace, math, emoji). The browser uses the first font that is installed or loaded with @font-face. Quote names with spaces. Inherited.",
     "body { font-family: \"Helvetica Neue\", Arial, sans-serif; }\ncode { font-family: ui-monospace, Consolas, monospace; }"),
    ("Fonts and text", "font-size", "length | percentage | keyword",
     "The size of the text. Use rem for predictable sizes that respect user preferences (1rem = 16px by default), em for sizes relative to the parent, and clamp() for fluid type. Keywords: xx-small to xxx-large, smaller, larger.",
     "html { font-size: 100%; }\nh1 { font-size: 2rem; }\np { font-size: clamp(1rem, 0.9rem + 0.5vw, 1.25rem); }"),
    ("Fonts and text", "font-weight", "normal | bold | bolder | lighter | 100-900",
     "Thickness of the strokes. 400 = normal, 700 = bold. Variable fonts support any value in between.",
     "strong { font-weight: 700; }\nh2 { font-weight: 600; }"),
    ("Fonts and text", "font-style", "normal | italic | oblique",
     "Italic or slanted text. <em>, <i>, <cite>, <var>, <dfn>, <address> are italic by default.",
     "em { font-style: italic; }\n.no-italic { font-style: normal; }"),
    ("Fonts and text", "font", "shorthand",
     "Shorthand for font-style, font-variant, font-weight, font-size/line-height and font-family in that order. Size and family are required.",
     "body { font: 16px/1.6 Arial, sans-serif; }\nh1 { font: bold 2rem Georgia, serif; }"),
    ("Fonts and text", "font-variant / font-variant-numeric / font-feature-settings", "various",
     "Typographic features: small caps, tabular numbers (align digits in tables), ligatures, fractions.",
     "td.num { font-variant-numeric: tabular-nums; }\n.caps { font-variant: small-caps; }"),
    ("Fonts and text", "@font-face", "at-rule",
     "Loads a custom font file so it can be used in font-family. Provide woff2, set font-display: swap to show fallback text while loading, and subset by unicode-range for speed.",
     "@font-face {\n  font-family: \"Cairo\";\n  src: url(\"cairo.woff2\") format(\"woff2\");\n  font-weight: 400 700;\n  font-display: swap;\n}\nbody { font-family: \"Cairo\", sans-serif; }"),
    ("Fonts and text", "line-height", "normal | number | length | percentage",
     "Height of each line of text. A unitless number (1.5) is best because it scales with the font size and is inherited as a factor. 1.4-1.6 is comfortable for body text.",
     "body { line-height: 1.6; }\nh1 { line-height: 1.1; }"),
    ("Fonts and text", "color", "colour",
     "The colour of the text (and the default for borders and currentColor). Inherited. Ensure at least 4.5:1 contrast with the background for body text.",
     "body { color: #1b2431; }\n.muted { color: #6b7280; }"),
    ("Fonts and text", "text-align", "start | end | left | right | center | justify",
     "Horizontal alignment of inline content inside a block. start/end follow the writing direction (best for multilingual sites). Justified text can create rivers of white space; use with hyphens: auto.",
     "footer { text-align: center; }\nth { text-align: start; }"),
    ("Fonts and text", "text-decoration", "none | underline | overline | line-through, style, colour, thickness",
     "Lines drawn on text. Shorthand for text-decoration-line, -style, -color, -thickness. Links are underlined by default; keep the underline or another clear indicator.",
     "a { text-decoration: none; }\na:hover { text-decoration: underline; }\n.spelling { text-decoration: red wavy underline; }"),
    ("Fonts and text", "text-transform", "none | capitalize | uppercase | lowercase",
     "Changes letter case for display without changing the HTML. Screen readers may spell out all-caps words.",
     "h2 { text-transform: uppercase; letter-spacing: 0.05em; }"),
    ("Fonts and text", "text-indent", "length | percentage",
     "Indentation of the first line of a block.", "p + p { text-indent: 1.5em; }"),
    ("Fonts and text", "text-shadow", "x y blur colour",
     "Shadow behind text. Several shadows may be listed.", "h1 { text-shadow: 0 2px 4px rgb(0 0 0 / 0.3); }"),
    ("Fonts and text", "letter-spacing / word-spacing", "normal | length",
     "Extra space between letters or words.", ".label { letter-spacing: 0.1em; }"),
    ("Fonts and text", "white-space", "normal | nowrap | pre | pre-wrap | pre-line | break-spaces",
     "How whitespace and line breaks in the source are handled. normal collapses spaces and wraps; nowrap collapses but never wraps; pre preserves everything (like <pre>); pre-wrap preserves but wraps; pre-line collapses spaces but keeps line breaks.",
     "pre { white-space: pre-wrap; }\n.nowrap { white-space: nowrap; }"),
    ("Fonts and text", "overflow-wrap / word-break / hyphens", "normal | break-word | anywhere / normal | break-all | keep-all / none | manual | auto",
     "Control breaking of long words. overflow-wrap: anywhere breaks only when needed to avoid overflow; word-break: break-all breaks anywhere; hyphens: auto adds hyphens based on lang.",
     "p { overflow-wrap: anywhere; hyphens: auto; }"),
    ("Fonts and text", "text-overflow", "clip | ellipsis",
     "What to show when text is clipped by overflow: hidden on a single line. Requires white-space: nowrap and overflow: hidden.",
     ".title { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }"),
    ("Fonts and text", "vertical-align", "baseline | sub | super | top | middle | bottom | text-top | text-bottom | length",
     "Vertical alignment of inline or table-cell content. Does not centre block elements; use flexbox for that.",
     "img.icon { vertical-align: middle; }\ntd { vertical-align: top; }"),
    ("Fonts and text", "direction / unicode-bidi / writing-mode", "ltr | rtl / normal | embed | isolate | bidi-override / horizontal-tb | vertical-rl | vertical-lr",
     "Text direction and writing mode. Prefer the HTML dir attribute over the CSS direction property. writing-mode enables vertical text for East Asian typography and rotated headings.",
     ".vertical { writing-mode: vertical-rl; }"),
    ("Fonts and text", "list-style", "shorthand: type position image",
     "Bullets and numbering for lists. list-style-type: disc, circle, square, decimal, lower-alpha, upper-roman, none, or a string. list-style-position: inside | outside. Applies to ul, ol and li.",
     "ul { list-style: square inside; }\nnav ul { list-style: none; padding: 0; }\nol { list-style-type: upper-roman; }\nli::marker { color: #e60000; }"),
    ("Fonts and text", "quotes", "pairs of strings",
     "Quotation marks used by <q> and open-quote/close-quote.", "q { quotes: '\u00ab' '\u00bb'; }"),
    ("Fonts and text", "content", "string | attr() | counter() | url() | open-quote | none",
     "Generated content for ::before and ::after.", "a[href^=\"http\"]::after { content: \" (\" attr(href) \")\"; }"),
    ("Fonts and text", "counter-reset / counter-increment", "name value",
     "CSS counters for automatic numbering of headings, figures, nested lists.",
     "body { counter-reset: fig; }\nfigcaption::before { counter-increment: fig; content: \"Figure \" counter(fig) \": \"; }"),
    ("Fonts and text", "tab-size", "integer | length", "Width of tab characters in <pre>.", "pre { tab-size: 2; }"),
    ("Fonts and text", "user-select", "auto | none | text | all", "Whether the user can select the text.", ".no-copy { user-select: none; }"),

    # Box model
    ("Box model", "width / height", "auto | length | percentage | min-content | max-content | fit-content",
     "Size of the box (content box by default; border box with box-sizing: border-box). Percentages are relative to the containing block. Prefer max-width for fluid layouts.",
     ".container { width: 100%; max-width: 1180px; }\nimg { width: 100%; height: auto; }"),
    ("Box model", "min-width / max-width / min-height / max-height", "length | percentage | none",
     "Limits on size. max-width: 100% on images stops them overflowing; min-height: 100vh makes a section fill the screen.",
     "img { max-width: 100%; }\nmain { min-height: 100dvh; }"),
    ("Box model", "aspect-ratio", "auto | ratio",
     "Preferred width-to-height ratio when one dimension is auto. Replaces the old padding-top hack for responsive video.",
     ".video { aspect-ratio: 16 / 9; width: 100%; }\n.avatar { aspect-ratio: 1; }"),
    ("Box model", "box-sizing", "content-box | border-box",
     "Whether width and height include padding and border. border-box is almost always what you want.",
     "*, *::before, *::after { box-sizing: border-box; }"),
    ("Box model", "margin", "length | percentage | auto (1-4 values)",
     "Space outside the border. One value: all sides; two: vertical horizontal; three: top horizontal bottom; four: top right bottom left (clockwise). margin: 0 auto centres a block with a width. Vertical margins collapse. Logical versions: margin-block, margin-inline.",
     "p { margin: 0 0 1em; }\n.box { margin: 20px auto; }\n.card { margin-inline: auto; }"),
    ("Box model", "padding", "length | percentage (1-4 values)",
     "Space between the content and the border. Same value order as margin. Cannot be negative. Backgrounds show through padding.",
     "button { padding: 10px 20px; }\n.card { padding-block: 1rem; padding-inline: 1.5rem; }"),
    ("Box model", "border", "width style colour",
     "Shorthand for border-width, border-style and border-color on all sides. Styles: none, solid, dashed, dotted, double, groove, ridge, inset, outset. Per-side: border-top, border-right, border-bottom, border-left, or logical border-block-start etc.",
     ".card { border: 1px solid #e7ddcb; }\nblockquote { border-left: 4px solid #c8a24a; }\nth, td { border-bottom: 1px solid #ddd; }"),
    ("Box model", "border-radius", "length | percentage (1-4 values, optional / for elliptical)",
     "Rounds the corners. 50% on a square makes a circle. Per-corner: border-top-left-radius etc.",
     ".btn { border-radius: 8px; }\n.avatar { border-radius: 50%; }\n.pill { border-radius: 999px; }"),
    ("Box model", "border-collapse / border-spacing", "separate | collapse / length",
     "Table borders: collapse merges adjacent cell borders into one; border-spacing sets the gap between cells in separate mode (replaces cellspacing).",
     "table { border-collapse: collapse; }\ntable.spaced { border-collapse: separate; border-spacing: 4px; }"),
    ("Box model", "outline", "width style colour",
     "A line drawn outside the border that does not take space. Browsers use it for the keyboard focus ring; never remove it without a replacement. outline-offset moves it away from the edge.",
     ":focus-visible { outline: 3px solid #1b6fd8; outline-offset: 2px; }"),
    ("Box model", "box-shadow", "x y blur spread colour [inset]",
     "Shadows around the box. Several shadows may be listed, separated by commas.",
     ".card { box-shadow: 0 10px 30px rgb(27 36 49 / 0.09); }\n.inset { box-shadow: inset 0 0 0 2px #e60000; }"),
    ("Box model", "overflow / overflow-x / overflow-y", "visible | hidden | clip | scroll | auto",
     "What happens when content is larger than the box. auto shows scrollbars only when needed. Setting overflow (other than visible) also clips absolutely positioned children and contains floats.",
     ".table-wrap { overflow-x: auto; }\n.modal-body { max-height: 70vh; overflow-y: auto; }"),
    ("Box model", "display", "block | inline | inline-block | flex | grid | none | contents | flow-root | list-item | table...",
     "How the element generates boxes and lays out its children. See the layout table in the CSS introduction.",
     "nav ul { display: flex; }\n.hidden { display: none; }\nspan.badge { display: inline-block; }"),
    ("Box model", "visibility", "visible | hidden | collapse",
     "hidden makes the element invisible but it still takes up space (unlike display: none). collapse removes table rows/columns.",
     ".placeholder { visibility: hidden; }"),
    ("Box model", "opacity", "0 to 1",
     "Transparency of the whole element including its children. 0 is invisible but still takes space and receives clicks.",
     ".disabled { opacity: 0.5; }\n.fade { transition: opacity 0.3s; }"),
    ("Box model", "object-fit / object-position", "fill | contain | cover | none | scale-down / position",
     "How a replaced element (img, video) fits its box when the box's ratio differs from the media. cover crops to fill; contain letterboxes.",
     ".thumb { width: 200px; height: 150px; object-fit: cover; object-position: center top; }"),
    ("Box model", "resize", "none | both | horizontal | vertical",
     "Whether the user can resize the element (textarea by default).", "textarea { resize: vertical; }"),
    ("Box model", "cursor", "auto | pointer | default | text | move | not-allowed | grab | wait | help | zoom-in | url()",
     "The mouse pointer shape over the element.", "button, [role=\"button\"] { cursor: pointer; }\n.disabled { cursor: not-allowed; }"),

    # Background
    ("Backgrounds", "background-color", "colour | transparent",
     "The colour behind the content and padding.", "body { background-color: #f6f1e7; }"),
    ("Backgrounds", "background-image", "url() | gradient | none",
     "One or more images or gradients layered behind the element, first listed on top. Gradients: linear-gradient(), radial-gradient(), conic-gradient(), repeating-*.",
     ".hero { background-image: linear-gradient(rgb(0 0 0 / 0.5), rgb(0 0 0 / 0.5)), url(hero.jpg); }"),
    ("Backgrounds", "background-size / background-position / background-repeat / background-attachment / background-clip / background-origin", "various",
     "How the image is sized (cover, contain, lengths), placed (center, top right, 50% 50%), repeated (no-repeat, repeat-x), scrolled (fixed for parallax), and which box it fills.",
     ".hero { background: url(hero.jpg) center / cover no-repeat; }"),
    ("Backgrounds", "background", "shorthand",
     "Shorthand for all background properties: color image position / size repeat attachment origin clip.",
     "footer { background: #222 url(pattern.png) repeat; }"),
    ("Backgrounds", "filter / backdrop-filter", "blur() | brightness() | contrast() | grayscale() | drop-shadow() | ...",
     "Graphical effects applied to the element or to what is behind it (frosted glass).",
     "img:hover { filter: brightness(1.1); }\n.glass { backdrop-filter: blur(10px); background: rgb(255 255 255 / 0.6); }"),
    ("Backgrounds", "mix-blend-mode / isolation", "normal | multiply | screen | overlay | difference...",
     "How the element blends with what is behind it.", ".logo { mix-blend-mode: multiply; }"),
    ("Backgrounds", "clip-path / mask", "shapes and images",
     "Clip the element to a shape (circle(), polygon(), inset()) or mask it with an image.",
     ".hex { clip-path: polygon(25% 0, 75% 0, 100% 50%, 75% 100%, 25% 100%, 0 50%); }"),

    # Layout
    ("Layout", "position / top / right / bottom / left / inset / z-index", "static | relative | absolute | fixed | sticky",
     "Positioning scheme and offsets. z-index orders positioned (and flex/grid) siblings on the z-axis; higher is in front; it creates stacking contexts.",
     ".modal { position: fixed; inset: 0; z-index: 1000; }\n.badge { position: absolute; top: -8px; right: -8px; }\nheader { position: sticky; top: 0; }"),
    ("Layout", "float / clear", "left | right | none / left | right | both",
     "Float takes an element out of flow and lets text wrap around it (its original purpose: images in text). Clear moves an element below floats. Not for page layout; use flex/grid.",
     "figure.left { float: left; margin: 0 1em 1em 0; }\n.after { clear: both; }"),
    ("Layout", "flex-direction / flex-wrap / flex-flow", "row | row-reverse | column | column-reverse / nowrap | wrap | wrap-reverse",
     "Direction of the main axis and whether items wrap. flex-flow is the shorthand.", ".row { display: flex; flex-flow: row wrap; }"),
    ("Layout", "justify-content", "flex-start | flex-end | center | space-between | space-around | space-evenly | start | end",
     "Distribution of items along the main axis (flex) or of grid tracks along the inline axis.", ".toolbar { display: flex; justify-content: space-between; }"),
    ("Layout", "align-items / align-self / align-content", "stretch | flex-start | flex-end | center | baseline | start | end",
     "Alignment on the cross axis: for all items, for one item, or for wrapped lines.", ".center { display: flex; align-items: center; justify-content: center; }"),
    ("Layout", "justify-items / justify-self / place-items / place-content / place-self", "start | end | center | stretch",
     "Grid inline-axis alignment and shorthands combining align and justify.", ".grid { display: grid; place-items: center; }"),
    ("Layout", "gap / row-gap / column-gap", "length | percentage",
     "Space between flex items, grid tracks or multi-column columns. Replaces margin hacks.", ".cards { display: grid; gap: 24px 16px; }"),
    ("Layout", "flex / flex-grow / flex-shrink / flex-basis", "number number length|auto",
     "How a flex item grows and shrinks relative to siblings and its starting size. flex: 1 = fill equally; flex: 0 0 200px = fixed 200px; flex: auto = size to content then grow.",
     ".sidebar { flex: 0 0 240px; }\n.content { flex: 1; min-width: 0; }"),
    ("Layout", "order", "integer", "Visual order of flex or grid items (does not change tab order; use sparingly).", ".first { order: -1; }"),
    ("Layout", "grid-template-columns / grid-template-rows", "track sizes: length, %, fr, auto, min-content, max-content, minmax(), repeat(), fit-content()",
     "Define the explicit grid tracks. repeat(auto-fit, minmax(240px, 1fr)) creates as many columns as fit.",
     ".layout { display: grid; grid-template-columns: 240px 1fr; }\n.gallery { grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); }"),
    ("Layout", "grid-template-areas / grid-area", "strings / name or line numbers",
     "Named regions for readable layouts. Items are placed with grid-area: name.",
     ".page { grid-template-areas: \"head head\" \"nav main\" \"foot foot\"; }\nfooter { grid-area: foot; }"),
    ("Layout", "grid-column / grid-row / grid-column-start etc.", "line / span n / name",
     "Place an item by grid lines. span 2 makes it cover two tracks.", ".wide { grid-column: 1 / -1; }\n.tall { grid-row: span 2; }"),
    ("Layout", "grid-auto-flow / grid-auto-rows / grid-auto-columns", "row | column | dense / track size",
     "How auto-placed items flow and how implicit tracks are sized.", ".masonry { grid-auto-flow: dense; grid-auto-rows: 120px; }"),
    ("Layout", "columns / column-count / column-width / column-gap / column-rule / column-span / break-inside", "various",
     "Multi-column text like a newspaper.", ".article { columns: 2 300px; column-gap: 32px; }\nfigure { break-inside: avoid; }"),
    ("Layout", "container-type / container-name / @container", "inline-size | size | normal",
     "Container queries: style an element based on the size of an ancestor container instead of the viewport.",
     ".sidebar { container-type: inline-size; }\n@container (max-width: 300px) { .card { flex-direction: column; } }"),
    ("Layout", "contain / content-visibility", "layout | paint | size | style / visible | hidden | auto",
     "Performance hints: isolate an element's rendering; content-visibility: auto skips rendering off-screen content.",
     ".long-list > li { content-visibility: auto; contain-intrinsic-size: auto 80px; }"),

    # Transforms, transitions, animations
    ("Motion", "transform / transform-origin / rotate / scale / translate", "translate() rotate() scale() skew() matrix() perspective()",
     "Move, rotate, scale or skew the element without affecting layout; hardware accelerated. The individual properties rotate, scale and translate can be set separately.",
     ".card:hover { transform: translateY(-4px) scale(1.02); }\n.spin { rotate: 45deg; }"),
    ("Motion", "transition / transition-property / -duration / -timing-function / -delay", "property time easing time",
     "Animate changes of properties smoothly. Timing functions: ease, linear, ease-in, ease-out, ease-in-out, cubic-bezier(), steps().",
     "a { transition: color 0.2s ease; }\n.panel { transition: transform 0.3s cubic-bezier(0.2, 0.8, 0.2, 1); }"),
    ("Motion", "animation / @keyframes", "name duration timing delay iteration-count direction fill-mode play-state",
     "Keyframe animations. Respect prefers-reduced-motion.",
     "@keyframes pulse { 50% { opacity: 0.5; } }\n.dot { animation: pulse 1s infinite; }"),
    ("Motion", "scroll-behavior / scroll-snap-type / scroll-snap-align / scroll-margin / scroll-padding / overscroll-behavior", "various",
     "Smooth scrolling, snap points for carousels, and offsets for fixed headers.",
     "html { scroll-behavior: smooth; scroll-padding-top: 80px; }\n.carousel { scroll-snap-type: x mandatory; }\n.carousel > * { scroll-snap-align: start; }"),
    ("Motion", "will-change", "property names",
     "Hint that a property will animate so the browser can optimise. Use sparingly.", ".drawer { will-change: transform; }"),

    # Interaction and misc
    ("Interaction", "pointer-events", "auto | none",
     "none makes the element ignore mouse/touch events (clicks pass through).", ".overlay-text { pointer-events: none; }"),
    ("Interaction", "accent-color", "colour",
     "Colour of native checkboxes, radios, range sliders and progress bars.", ":root { accent-color: #e60000; }"),
    ("Interaction", "appearance", "none | auto | base-select",
     "Remove or keep the native look of form controls. none lets you restyle selects and inputs fully.", "select { appearance: none; }"),
    ("Interaction", "color-scheme", "light | dark | light dark",
     "Tells the browser which colour schemes the page supports so form controls and scrollbars match.", ":root { color-scheme: light dark; }"),
    ("Interaction", "caret-color", "colour", "Colour of the text cursor.", "input { caret-color: #e60000; }"),
    ("Interaction", "touch-action", "auto | none | pan-x | pan-y | manipulation",
     "Which touch gestures the browser handles; manipulation removes the 300ms tap delay on old mobile browsers.", "button { touch-action: manipulation; }"),
    ("Interaction", "field-sizing", "fixed | content", "Make inputs and textareas grow with their content.", "textarea { field-sizing: content; }"),
    ("Interaction", "all", "initial | inherit | unset | revert", "Reset every property at once.", ".reset { all: unset; }"),
    ("Interaction", "@media", "at-rule",
     "Conditional rules based on viewport size, orientation, resolution, hover ability, user preferences (prefers-color-scheme, prefers-reduced-motion, prefers-contrast) and output (print, screen).",
     "@media (max-width: 600px) { nav { display: none; } }\n@media (hover: hover) { a:hover { color: red; } }"),
    ("Interaction", "@supports", "at-rule", "Apply rules only if the browser supports a feature.", "@supports (display: grid) { .layout { display: grid; } }"),
    ("Interaction", "@import / @layer / @scope / @property", "at-rules",
     "Import other style sheets (slow; prefer <link>), define cascade layers, scope styles to a subtree, register typed custom properties.",
     "@layer reset, base, components;\n@layer base { body { margin: 0; } }"),
    ("Interaction", "@page", "at-rule", "Page size and margins for printing.", "@page { size: A4; margin: 2cm; }"),
]

CSS_HTML_STYLING_GUIDE = [
    ("h2", "Styling common HTML elements: a cookbook"),
    ("h3", "A sensible reset"),
    ("code", "*, *::before, *::after { box-sizing: border-box; }\nbody { margin: 0; font-family: system-ui, -apple-system, \"Segoe UI\", Roboto, Arial, sans-serif; line-height: 1.6; color: #1b2431; }\nimg, video, svg { max-width: 100%; height: auto; display: block; }\nbutton, input, select, textarea { font: inherit; color: inherit; }\nh1, h2, h3, h4 { line-height: 1.2; margin-block: 0 0.5em; }\np, ul, ol, dl, table, figure, pre { margin-block: 0 1em; }"),
    ("h3", "Links"),
    ("code", "a { color: #0b57d0; text-underline-offset: 2px; }\na:hover { color: #083b8f; }\na:focus-visible { outline: 3px solid #0b57d0; outline-offset: 2px; border-radius: 2px; }\na[href^=\"http\"]:not([href*=\"mysite.com\"])::after { content: \" \u2197\"; font-size: 0.8em; }"),
    ("h3", "Headings with a fluid scale"),
    ("code", "h1 { font-size: clamp(1.8rem, 1.2rem + 2.5vw, 3rem); }\nh2 { font-size: clamp(1.4rem, 1rem + 1.5vw, 2rem); }\nh3 { font-size: 1.25rem; }"),
    ("h3", "Lists"),
    ("code", "/* Default bullets tweaked */\nul { padding-inline-start: 1.25em; }\nli + li { margin-top: 0.25em; }\nli::marker { color: #e60000; }\n\n/* Bullet-less horizontal menu */\n.menu { list-style: none; margin: 0; padding: 0; display: flex; gap: 1rem; }\n\n/* Custom check bullets */\n.checks { list-style: none; padding: 0; }\n.checks li::before { content: \"\u2713 \"; color: #0f8a4c; font-weight: bold; }\n\n/* Description list as a two-column grid */\ndl.specs { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1rem; }\ndl.specs dt { font-weight: 600; }\ndl.specs dd { margin: 0; }"),
    ("h3", "Tables"),
    ("code", "table { border-collapse: collapse; width: 100%; font-variant-numeric: tabular-nums; }\ncaption { caption-side: top; text-align: start; font-weight: 600; padding-block: 0.5rem; }\nth, td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #e5e5e5; text-align: start; vertical-align: top; }\nthead th { background: #f5f5f5; position: sticky; top: 0; }\ntbody tr:nth-child(even) { background: #fafafa; }\ntbody tr:hover { background: #fff4e0; }\ntd.num, th.num { text-align: end; }\n.table-wrap { overflow-x: auto; }   /* wrap the table for small screens */\n\n/* Stacked table on phones */\n@media (max-width: 600px) {\n  .stack thead { display: none; }\n  .stack tr { display: block; margin-bottom: 1rem; border: 1px solid #ddd; }\n  .stack td { display: flex; justify-content: space-between; }\n  .stack td::before { content: attr(data-label); font-weight: 600; }\n}"),
    ("h3", "Forms"),
    ("code", ".field { display: grid; gap: 0.25rem; margin-bottom: 1rem; }\nlabel { font-weight: 600; }\ninput, select, textarea { padding: 0.6rem 0.75rem; border: 1px solid #c9c9c9; border-radius: 8px; background: #fff; }\ninput:focus-visible, select:focus-visible, textarea:focus-visible { outline: 3px solid #0b57d0; outline-offset: 1px; border-color: #0b57d0; }\ninput:user-invalid { border-color: #b90000; }\ninput:disabled { background: #f0f0f0; cursor: not-allowed; }\n::placeholder { color: #8a8a8a; }\nfieldset { border: 1px solid #ddd; border-radius: 8px; padding: 1rem; }\nlegend { padding: 0 0.5rem; font-weight: 600; }\ninput[type=\"checkbox\"], input[type=\"radio\"] { width: 1.1em; height: 1.1em; accent-color: #e60000; }\nbutton { padding: 0.65rem 1.25rem; border: 0; border-radius: 8px; background: #e60000; color: #fff; font-weight: 600; cursor: pointer; }\nbutton:hover { background: #b90000; }\nbutton:disabled { opacity: 0.5; cursor: not-allowed; }"),
    ("h3", "Header, nav, main, footer layout"),
    ("code", "body { min-height: 100dvh; display: flex; flex-direction: column; }\nheader { position: sticky; top: 0; z-index: 10; background: #fff; box-shadow: 0 1px 0 #eee; }\nheader .wrap { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: 0.75rem 1rem; }\nnav ul { display: flex; gap: 1.25rem; list-style: none; margin: 0; padding: 0; }\nnav a[aria-current=\"page\"] { border-bottom: 2px solid #e60000; }\nmain { flex: 1; width: min(100% - 2rem, 1180px); margin-inline: auto; padding-block: 2rem; }\nfooter { background: #222; color: #ddd; text-align: center; padding: 2rem 1rem; margin-top: auto; }\nfooter a { color: #ffd166; }"),
    ("h3", "Images and figures"),
    ("code", "figure { margin: 0 0 1.5rem; }\nfigure img { border-radius: 12px; }\nfigcaption { font-size: 0.9rem; color: #666; margin-top: 0.5rem; text-align: center; }\n.avatar { width: 64px; aspect-ratio: 1; border-radius: 50%; object-fit: cover; }\n.hero img { width: 100%; height: 50vh; object-fit: cover; }"),
    ("h3", "Code and pre"),
    ("code", "code { font-family: ui-monospace, Consolas, \"Courier New\", monospace; font-size: 0.95em; background: #f4f4f4; padding: 0.1em 0.3em; border-radius: 4px; }\npre { background: #1e1e1e; color: #eee; padding: 1rem; border-radius: 8px; overflow-x: auto; tab-size: 2; }\npre code { background: none; padding: 0; color: inherit; }\nkbd { border: 1px solid #bbb; border-bottom-width: 2px; border-radius: 4px; padding: 0 0.35em; background: #fafafa; font-size: 0.9em; }"),
    ("h3", "Blockquote, hr, details"),
    ("code", "blockquote { margin: 1.5rem 0; padding: 0.75rem 1.25rem; border-inline-start: 4px solid #c8a24a; background: #fdf8f0; }\nblockquote footer { font-size: 0.9rem; color: #666; }\nhr { border: 0; border-top: 1px solid #e0e0e0; margin: 2rem 0; }\ndetails { border: 1px solid #ddd; border-radius: 8px; padding: 0.5rem 1rem; }\nsummary { cursor: pointer; font-weight: 600; }\ndetails[open] summary { margin-bottom: 0.5rem; }"),
    ("h3", "Dialog and popover"),
    ("code", "dialog { border: 0; border-radius: 16px; padding: 1.5rem; max-width: min(90vw, 480px); box-shadow: 0 24px 60px rgb(0 0 0 / 0.25); }\ndialog::backdrop { background: rgb(0 0 0 / 0.5); backdrop-filter: blur(2px); }\n[popover] { border: 1px solid #ddd; border-radius: 12px; padding: 1rem; box-shadow: 0 10px 30px rgb(0 0 0 / 0.15); }\n[popover]:popover-open { animation: fade-in 0.15s ease-out; }"),
    ("h3", "Visually hidden (for screen readers only)"),
    ("code", ".sr-only {\n  position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;\n  overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; border: 0;\n}"),
    ("h3", "Dark mode"),
    ("code", ":root { color-scheme: light dark; --bg: #fff; --ink: #1b2431; }\n@media (prefers-color-scheme: dark) { :root { --bg: #111; --ink: #eee; } }\nbody { background: var(--bg); color: var(--ink); }"),
]


# ---------------------------------------------------------------------------
# Lists and tables with CSS (based on the W3Schools "HTML & CSS Lists and Tables"
# lesson and the CSS Lists / CSS Tables chapters)
# ---------------------------------------------------------------------------
CSS_LISTS_TABLES = [
    ("p", "Lists group related items; tables display structured data (information arranged in rows and columns so "
          "that it is easy to scan). Combining the right HTML element with a little CSS makes both far more readable "
          "and accessible. This chapter walks through every common styling task for <ul>, <ol>, <dl> and <table>, "
          "step by step, with complete copy-and-paste examples."),
    ("h2", "1. Unordered and ordered lists"),
    ("p", "Use <ul> for unordered lists (bullets) and <ol> for ordered lists (numbers). Each item goes in an <li>. "
          "The browser adds the bullets or numbers automatically, indents the list about 40 pixels and adds a blank line "
          "before and after it."),
    ("code", "<ul class=\"features\">\n  <li>Responsive layout</li>\n  <li>Semantic HTML</li>\n  <li>Accessible components</li>\n</ul>\n\n<ol class=\"steps\">\n  <li>Plan content</li>\n  <li>Structure markup</li>\n  <li>Apply typography and layout</li>\n</ol>"),
    ("h3", "Changing the marker: list-style-type"),
    ("p", "The list-style-type property chooses the bullet or numbering style. It replaces the obsolete HTML type attribute."),
    ("table", [["Value", "Works on", "Result"],
               ["disc (default for ul)", "ul", "Filled circle"], ["circle", "ul", "Hollow circle"], ["square", "ul", "Filled square"],
               ["none", "ul, ol", "No marker at all (used for menus and navigation)"],
               ["decimal (default for ol)", "ol", "1, 2, 3"], ["decimal-leading-zero", "ol", "01, 02, 03"],
               ["lower-alpha / upper-alpha", "ol", "a, b, c / A, B, C"], ["lower-roman / upper-roman", "ol", "i, ii, iii / I, II, III"],
               ["lower-greek", "ol", "alpha, beta, gamma"], ["arabic-indic", "ol", "Arabic-Indic digits used in Arabic-language pages"],
               ["'\\2192 ' or any string", "ul", "A custom character such as an arrow or a check mark"]]),
    ("code", "ul.a { list-style-type: circle; }\nul.b { list-style-type: square; }\nol.c { list-style-type: upper-roman; }\nol.d { list-style-type: lower-alpha; }\nul.arrows { list-style-type: '\\2192 '; }   /* a right arrow before every item */"),
    ("h3", "Image markers and marker position"),
    ("code", "ul { list-style-image: url('sqpurple.gif'); }\n\n/* inside: the marker is part of the text and wraps with it;\n   outside (default): the marker hangs in the left margin */\nul.inside  { list-style-position: inside; }\nul.outside { list-style-position: outside; }"),
    ("h3", "The list-style shorthand"),
    ("p", "list-style sets type, position and image in one declaration, in that order. Missing values return to their defaults."),
    ("code", "ul { list-style: square inside url('sqpurple.gif'); }"),
    ("h3", "Removing default settings"),
    ("p", "To use a list as a menu, remove the marker, the margin and the padding. Setting margin and padding to 0 on the <ul> "
          "removes the indentation that browsers add; without this step the items still sit 40 pixels from the left edge."),
    ("code", "ul.menu {\n  list-style-type: none;\n  margin: 0;\n  padding: 0;\n}"),
    ("h3", "Styling the marker itself: ::marker"),
    ("p", "The ::marker pseudo-element styles only the bullet or number, leaving the item text alone. It accepts colour, "
          "font and content properties."),
    ("code", "li::marker { color: #b90000; font-weight: bold; }\nol li::marker { content: counter(list-item) ') '; }"),
    ("h3", "Custom markers with ::before (the W3Schools 'features' pattern)"),
    ("p", "For complete control replace the marker with generated content. The rules below remove the default bullets, "
          "space the items with Grid gap, give every item a card look and insert a check mark with ::before."),
    ("code", ".features {\n  list-style: none;\n  padding: 0;\n  margin: 0;\n  display: grid;\n  gap: 12px;\n}\n.features li {\n  padding: 16px 20px;\n  background: #fff;\n  border-radius: 12px;\n  box-shadow: 0 10px 25px rgba(15, 23, 42, 0.08);\n}\n.features li::before {\n  content: '\\2714';      /* heavy check mark */\n  color: #04AA6D;\n  margin-right: 12px;\n}"),
    ("h3", "Colouring lists"),
    ("p", "Anything added to the <ul> or <ol> affects the whole list; anything added to <li> affects one item. Padding on the list "
          "moves the markers inward as well."),
    ("code", "ol {\n  background: #ff9999;\n  padding: 20px;\n}\nul {\n  background: #3399ff;\n  padding: 20px;\n}\nol li {\n  background: #ffe5e5;\n  color: darkred;\n  padding: 5px;\n  margin-left: 35px;\n}\nul li {\n  background: #cce5ff;\n  color: darkblue;\n  margin: 5px;\n}"),
    ("h3", "Horizontal lists: navigation bars"),
    ("p", "A navigation bar is just a list of links laid out in a row. Flexbox is the modern way; float was used before 2015."),
    ("code", "<nav>\n  <ul class=\"navbar\">\n    <li><a href=\"index.html\">Home</a></li>\n    <li><a href=\"books.html\">Books</a></li>\n    <li><a href=\"contact.html\">Contact</a></li>\n  </ul>\n</nav>\n\n<style>\n.navbar {\n  list-style: none;\n  margin: 0;\n  padding: 0;\n  display: flex;\n  gap: 4px;\n  background: #333;\n}\n.navbar a {\n  display: block;\n  padding: 14px 16px;\n  color: white;\n  text-decoration: none;\n}\n.navbar a:hover { background: #111; }\n</style>"),
    ("h3", "Numbered lists with counters"),
    ("p", "CSS counters number anything, including nested headings, and let you style the number separately."),
    ("code", "ol.fancy { counter-reset: item; list-style: none; padding: 0; }\nol.fancy li { counter-increment: item; margin: 8px 0; }\nol.fancy li::before {\n  content: counter(item);\n  display: inline-block;\n  width: 1.6em; height: 1.6em; line-height: 1.6em;\n  margin-right: .6em;\n  text-align: center;\n  border-radius: 50%;\n  background: #b90000;\n  color: white;\n  font-weight: bold;\n}"),
    ("h2", "2. Description lists"),
    ("p", "Use <dl> with <dt> (term) and <dd> (definition) for glossaries or metadata. Browsers indent the <dd> by about 40 pixels; "
          "with CSS Grid you can lay terms and definitions out in two columns."),
    ("code", "<dl class=\"glossary\">\n  <dt>HTML</dt>\n  <dd>Structure of a web page.</dd>\n  <dt>CSS</dt>\n  <dd>Presentation and layout.</dd>\n</dl>\n\n<style>\n.glossary {\n  display: grid;\n  grid-template-columns: max-content 1fr;\n  gap: 6px 16px;\n}\n.glossary dt { font-weight: bold; color: #b90000; }\n.glossary dd { margin: 0; }\n</style>"),
    ("h2", "3. HTML tables"),
    ("p", "<table> organises tabular data with rows (<tr>), header cells (<th>) and data cells (<td>). Tabular data is information "
          "best shown in a grid, such as price lists or schedules. Group the header row in <thead> and the data in <tbody>, and give "
          "every <th> a scope attribute so screen readers know whether it labels a column or a row."),
    ("code", "<table class=\"pricing\">\n  <caption>Subscription plans</caption>\n  <thead>\n    <tr>\n      <th scope=\"col\">Plan</th>\n      <th scope=\"col\">Price</th>\n      <th scope=\"col\">Features</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th scope=\"row\">Starter</th>\n      <td>$0</td>\n      <td>Basic components</td>\n    </tr>\n    <tr>\n      <th scope=\"row\">Pro</th>\n      <td>$19</td>\n      <td>Advanced layouts</td>\n    </tr>\n  </tbody>\n</table>"),
    ("h3", "Table borders"),
    ("p", "A table has no visible borders by default. The border property must be set on the table AND on the cells; setting it on "
          "the table alone draws only the outer frame. Because each cell has its own border you get a double line between cells "
          "until you collapse them."),
    ("code", "table, th, td {\n  border: 1px solid black;\n}"),
    ("h3", "Collapsed borders"),
    ("p", "border-collapse: collapse merges adjacent cell borders into a single line. This is almost always what you want. "
          "The old HTML cellspacing attribute is replaced by border-spacing (only in the separate model) and cellpadding by padding on the cells."),
    ("code", "table {\n  border-collapse: collapse;\n}\nth, td {\n  border: 1px solid #ddd;\n  padding: 8px;\n}\n\n/* alternative: keep separate borders but control the gap */\ntable.spaced { border-collapse: separate; border-spacing: 6px 2px; }"),
    ("h3", "Rounded or borderless tables"),
    ("p", "For a light look, add only a bottom border to each row. For rounded corners set overflow: hidden and border-radius on the table."),
    ("code", "table { border-collapse: collapse; width: 100%; }\ntd, th { border-bottom: 1px solid #ddd; padding: 12px; }\n\ntable.rounded { border-radius: 12px; overflow: hidden; }"),
    ("h3", "Table size"),
    ("p", "Width and height are set with CSS width and height on the table, rows or cells. width: 100% makes the table fill its container. "
          "The obsolete HTML width attribute did the same job."),
    ("code", "table { width: 100%; }\nth { height: 70px; }\ntd.narrow { width: 70px; }\ntable.fixed { table-layout: fixed; }   /* equal columns regardless of content */"),
    ("h3", "Alignment"),
    ("p", "text-align sets horizontal alignment (th content is centred and bold by default, td content is left aligned); "
          "vertical-align sets vertical alignment (middle by default). These replace the align and valign attributes."),
    ("code", "th { text-align: left; }\ntd { text-align: center; height: 50px; vertical-align: bottom; }"),
    ("h3", "Padding and spacing"),
    ("p", "padding on th/td controls the space between the border and the content. To add space between cells themselves use "
          "border-spacing (separate border model only)."),
    ("code", "th, td { padding: 15px; }\nth, td { padding-top: 10px; padding-bottom: 20px; padding-left: 30px; padding-right: 40px; }"),
    ("h3", "Horizontal dividers, hover and zebra stripes"),
    ("p", "Highlight rows on hover with :hover on <tr>, and zebra-stripe with :nth-child(even). Both make long tables easier to read."),
    ("code", "tr:hover { background-color: coral; }\ntr:nth-child(even) { background-color: #f2f2f2; }\n\n/* vertical zebra stripes */\nth:nth-child(even), td:nth-child(even) { background-color: #d6eeee; }\n\n/* combining both with transparency */\ntr:nth-child(even) { background-color: rgba(150, 212, 212, 0.4); }\nth:nth-child(even), td:nth-child(even) { background-color: rgba(150, 212, 212, 0.4); }"),
    ("h3", "Styling the header row"),
    ("code", ".pricing {\n  width: 100%;\n  border-collapse: collapse;\n  background: #fff;\n  border-radius: 12px;\n  overflow: hidden;\n}\n.pricing th, .pricing td {\n  padding: 16px 20px;\n  text-align: left;\n}\n.pricing thead {\n  background: #04AA6D;\n  color: #fff;\n}\n.pricing tbody tr:nth-child(even) {\n  background: #f9fafb;\n}"),
    ("p", "Key rules: border-collapse: collapse removes gaps, header styling highlights the labels, and :nth-child(even) zebra-stripes the rows."),
    ("h3", "Colouring individual columns"),
    ("code", "<table>\n  <colgroup>\n    <col span=\"2\" style=\"background-color: #D6EEEE\">\n  </colgroup>\n  <tr><th>MON</th><th>TUE</th><th>WED</th></tr>\n  ...\n</table>"),
    ("p", "Only a few properties work on <col>: width, visibility, background and border. For anything else target td:nth-child(n)."),
    ("h3", "Responsive tables"),
    ("p", "Tables can overflow on small screens. Wrapping them in a scroll container preserves readability: mobile users swipe "
          "sideways instead of the table breaking the layout. The wrapper is a <div> with overflow-x: auto."),
    ("code", "<div class=\"table-wrapper\">\n  <table>...</table>\n</div>\n\n<style>\n.table-wrapper { overflow-x: auto; }\n</style>"),
    ("p", "An alternative for narrow screens is to turn each row into a block and print the column label with a data attribute:"),
    ("code", "@media (max-width: 600px) {\n  thead { display: none; }\n  tr { display: block; margin-bottom: 1em; border: 1px solid #ddd; }\n  td { display: flex; justify-content: space-between; padding: 8px; }\n  td::before { content: attr(data-label); font-weight: bold; }\n}\n\n<!-- HTML -->\n<td data-label=\"Price\">$19</td>"),
    ("h3", "Sticky header and caption position"),
    ("code", "thead th { position: sticky; top: 0; background: #fff; }\ncaption { caption-side: bottom; font-style: italic; padding: 8px; }\ntable.no-empty { empty-cells: hide; }"),
    ("h2", "4. Accessibility tips for tables"),
    ("ul", ["Always use <th> for headers and add the scope attribute (col or row). It tells assistive technology which header belongs to which cell.",
            "Provide captions with <caption> when the table's purpose is not obvious from the surrounding text.",
            "Keep tables for data, not layout. Use CSS Grid or Flexbox for page layout.",
            "Do not rely on colour alone (for example a red cell for 'sold out'); add text or an icon as well.",
            "Avoid merged cells (rowspan/colspan) in data tables where possible; if you need them, add headers/id associations.",
            "Right-align numbers so that digits line up, and use the same number of decimals in a column."]),
    ("h2", "5. Complete example: course outline with a list and a table"),
    ("p", "This demo pairs a topic list with a simple table. The list uses square bullets while the table collapses its borders for a "
          "clean grid, with coloured headers to improve readability."),
    ("code", "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>Course Outline</title>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Course Outline</h1>\n  <ul>\n    <li>HTML Basics</li>\n    <li>CSS Essentials</li>\n    <li>Responsive Layouts</li>\n  </ul>\n  <table>\n    <tr><th>Module</th><th>Duration</th></tr>\n    <tr><td>Getting Started</td><td>2 hrs</td></tr>\n    <tr><td>Flexbox &amp; Grid</td><td>3 hrs</td></tr>\n  </table>\n</body>\n</html>"),
    ("code", "/* styles.css */\nbody {\n  font-family: 'Segoe UI', sans-serif;\n  padding: 48px;\n  background: #eef2ff;\n}\nul {\n  list-style: square;\n}\ntable {\n  margin-top: 32px;\n  border-collapse: collapse;\n  width: 100%;\n  max-width: 640px;\n  background: #fff;\n}\nth, td {\n  border: 1px solid #d9e2ec;\n  padding: 12px 16px;\n  text-align: left;\n}\nth {\n  background: #6366f1;\n  color: #fff;\n}"),
    ("h2", "6. Quick reference: list and table properties"),
    ("table", [["Property", "Applies to", "Purpose"],
               ["list-style-type", "ul, ol, li", "Marker shape or numbering system"], ["list-style-image", "ul, ol, li", "Image as marker"],
               ["list-style-position", "ul, ol, li", "Marker inside or outside the item box"], ["list-style", "ul, ol, li", "Shorthand for the three above"],
               ["::marker", "li", "Style the marker only"], ["counter-reset / counter-increment / counter()", "any", "Custom numbering"],
               ["border-collapse", "table", "collapse or separate cell borders"], ["border-spacing", "table", "Gap between cells (separate model)"],
               ["caption-side", "table", "Caption above (top) or below (bottom)"], ["empty-cells", "table", "show or hide borders of empty cells"],
               ["table-layout", "table", "auto (content sized) or fixed (equal, faster)"], ["vertical-align", "td, th", "top, middle, bottom"],
               ["text-align", "td, th", "left, center, right"], ["padding", "td, th", "Space inside cells (replaces cellpadding)"],
               [":nth-child(even/odd)", "tr, td", "Zebra stripes"], ["tr:hover", "tr", "Row highlight"], ["overflow-x: auto", "wrapper div", "Scrollable table on small screens"]]),
    ("h2", "7. Old HTML attributes and their CSS replacements"),
    ("table", [["Old attribute (HTML 3.2 / 4)", "Element", "Use instead"],
               ["type=\"square\"", "ul", "list-style-type: square"], ["type=\"A\" / type=\"i\"", "ol", "list-style-type: upper-alpha / lower-roman (type on ol is still allowed but CSS is preferred)"],
               ["compact", "ul, ol, dl", "margin / line-height"], ["border=\"1\"", "table", "border on table, th, td"], ["cellpadding", "table", "padding on th, td"],
               ["cellspacing", "table", "border-spacing (or border-collapse: collapse)"], ["width / height", "table, td", "width / height in CSS"],
               ["bgcolor", "table, tr, td", "background-color"], ["align", "table, tr, td", "text-align / margin: 0 auto"], ["valign", "tr, td", "vertical-align"],
               ["nowrap", "td", "white-space: nowrap"], ["frame / rules", "table", "border on the relevant sides"], ["summary", "table", "<caption> or aria-describedby"]]),
]
